-- 063_prices_live_table.sql — Move the digiquant.io live price feed off the forgeable
-- Realtime BROADCAST channel and onto a postgres-owned table streamed via Realtime
-- `postgres_changes` (#1807). Supersedes the withdrawn migration 062.
--
-- Run with:  supabase db push   (or apply via MCP against this project).
--
-- THE HOLE THIS CLOSES
-- --------------------
-- `prices:live` was a *public* Realtime broadcast channel. `anon` holds INSERT on
-- `realtime.messages` (a Supabase platform grant), and `pg_policies WHERE schemaname =
-- 'realtime'` returns ZERO rows, so RLS denied nothing. The anon key ships in plaintext in
-- every digiquant.io JS bundle and this repo is public, so anyone could POST to
-- /realtime/v1/api/broadcast and put forged quotes on `prices:live`; every open tab would
-- render them as live Finnhub data. The `prices-live` edge function was bypassed entirely,
-- which is why the invocation secret added in #1756 / PR #1790 never covered this path.
--
-- WHY MIGRATION 062'S FIX WAS WITHDRAWN — IT CANNOT BE APPLIED, EVER
-- -----------------------------------------------------------------
-- 062 tried to close the hole where the hole is: RLS policies on `realtime.messages`
-- (anon may SELECT, only service_role may INSERT) paired with `config: { private: true }`
-- on both clients. That is the textbook Supabase answer, and it is unreachable from this
-- migration chain. Verified read-only against the live `core` project on 2026-08-01 —
-- these five facts are load-bearing, and they are recorded here so the next reader does
-- not spend a day rediscovering them:
--
--   1. `realtime.messages` is owned by `supabase_realtime_admin`, not by `postgres`.
--   2. `supabase_realtime_admin` has ZERO members, and ZERO roles hold ADMIN OPTION on
--      it — so no role reachable from here can grant it to anybody, including itself.
--   3. Our connection is `postgres`, with `rolsuper = false`, and it is not a member:
--      `pg_has_role('postgres', 'supabase_realtime_admin', 'USAGE')` → false.
--   4. On PostgreSQL 17.6 (this project's version) `CREATEROLE` no longer implies
--      implicit admin over arbitrary pre-existing roles, so the usual escape hatch of
--      "the migration role can just grant itself the owner role" is closed by design.
--   5. `CREATE POLICY` requires table ownership. With 1–4, it raises
--      `42501 must be owner of table messages` — unfixable without Supabase platform
--      staff acting on the project directly.
--
-- 062 therefore could never be recorded as applied. db-migrate.yml pipes each file above
-- BASELINE_THROUGH through `psql --single-transaction -v ON_ERROR_STOP=1` together with
-- its own ledger INSERT, so 062's ownership preflight raised, the transaction rolled back,
-- and no `olympus_schema_migrations` row was ever written. Deleting the file is thus a
-- clean withdrawal: there is no orphan ledger row to reconcile and no tombstone needed.
-- The number 062 is burned on purpose and must not be reused, exactly like 037, 038 and
-- 059 — "migration 062" already means the abandoned `realtime.messages` approach in the
-- git history, in PR #1813, and in the docs of that era.
--
-- WHY A POSTGRES-OWNED TABLE CLOSES THE HOLE STRUCTURALLY
-- ------------------------------------------------------
-- The transport moves onto objects we actually own, so the control moves from a table we
-- cannot police to one we can:
--
--   * Forgery becomes impossible rather than merely disallowed. A broadcast payload
--     originates from whoever POSTed it; a `postgres_changes` payload is generated by
--     Realtime from the WAL. There is no client-supplied path into the WAL. To put a fake
--     quote on this feed you must first write the row — and no anon-reachable credential
--     can write this table (RLS enabled below, with no INSERT/UPDATE/DELETE policy, and
--     the matching grants revoked).
--   * The absent write policy IS the security control. Under RLS, absent policy = deny.
--     Do NOT "complete" the policy set below by adding an INSERT or UPDATE policy for
--     `anon` or `authenticated` — the omission is the fix, not an oversight.
--   * `service_role` carries `rolbypassrls` and is the only writer (the `prices-live`
--     edge function). Its write grant is stated explicitly at the bottom of this file
--     rather than inherited, for the reason recorded there.
--
-- Throughput is a non-issue and does not need revisiting: the publisher runs ONCE per
-- minute under pg_cron over <= 40 symbols, so this is at most ~40 WAL-sourced events per
-- minute, against the tens of thousands per second `postgres_changes` is built for.
--
-- `anon` KEEPS ITS INSERT GRANT ON `realtime.messages`, AND THAT IS NOW FINE
-- --------------------------------------------------------------------------
-- We are not revoking it and could not if we wanted to — it is a Supabase
-- platform-managed grant, unsupported to remove and reverted by the platform. It stops
-- mattering for this feed because nothing subscribes to `prices:live` any more. An
-- attacker can still push a message onto that broadcast topic; with no subscriber, it
-- lands in an empty room. The exposure was never the INSERT grant on its own, it was the
-- INSERT grant plus a listening client, and this migration removes the listener's reason
-- to exist. Anything added later that subscribes to a broadcast topic on this project
-- reopens the hole and inherits every constraint in the section above — read it first.
--
-- WHY `ALTER PUBLICATION` WORKS HERE WHEN `CREATE POLICY` DID NOT
-- --------------------------------------------------------------
-- The obvious next question, answered up front so it is not re-litigated: the
-- `supabase_realtime` publication is owned by `postgres`, and every relation in `public`
-- is owned by `postgres` (verified 2026-08-01, same session as the facts above).
-- `ALTER PUBLICATION ... ADD TABLE` requires ownership of the publication and of the
-- table being added; we hold both. Nothing in this file touches an object owned by
-- `supabase_realtime_admin`, which is precisely why it is appliable and 062 was not.
--
-- Idempotent throughout: CREATE TABLE IF NOT EXISTS, DROP POLICY IF EXISTS before CREATE
-- POLICY, ENABLE ROW LEVEL SECURITY is a no-op when already enabled, REPLICA IDENTITY is
-- a set-state statement, REVOKE/GRANT are re-runnable, and the publication membership is
-- guarded on `pg_publication_tables` because `ALTER PUBLICATION ... ADD TABLE` errors when
-- the table is already a member.
--
-- No `BEGIN;` anywhere on purpose — db-migrate.yml greps for one (case-insensitively, and
-- it does not skip `--` comments) and would then run this file bare, dropping
-- `--single-transaction` and splitting the ledger INSERT into a separate psql call. This
-- file wants to be wrapped by the deploy script. If you edit the prose above, keep the
-- token backticked as it is here; an unquoted one in a sentence is enough to flip the
-- branch, and nothing but the unit test for this file will catch it.

CREATE TABLE IF NOT EXISTS public.prices_live (
  ticker      text PRIMARY KEY,
  price       double precision NOT NULL,
  change      double precision,
  change_pct  double precision,
  quoted_at   timestamptz NOT NULL,
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- No CHECK constraints and no secondary index, both deliberate — note that this departs
-- from 055_instruments.sql, which does constrain ticker casing, so the divergence is
-- argued rather than accidental. A `price > 0` check would reject the legitimate zero
-- Finnhub returns for a halted or unrecognised symbol. A ticker-casing check would turn a
-- publisher bug into a 23514 that fails the whole minute's upsert instead of one row —
-- the exact failure mode the `documents` doc_type/category constraints produced again and
-- again (#628, #1005, #1383; migrations 014, 019, 020, 023, 027, 045 are all that churn).
-- A quote cache is throwaway data refreshed every 60s; it should degrade, not abort.
-- At <= 40 rows the primary key is the only access path worth having.

-- REPLICA IDENTITY DEFAULT (the primary key) is correct here and is set explicitly rather
-- than left to the default, so the choice is a decision on the record instead of an
-- accident. Realtime needs an identity to attach to each `postgres_changes` event; with
-- DEFAULT it uses `ticker`, and every UPDATE event carries the full new row, which is all
-- the browser consumes. We never need `old_record`.
--
-- What would force `FULL` — the only two cases, so a future reader can tell quickly
-- whether this line still holds:
--   * a SELECT policy whose USING clause reads a NON-KEY column. Realtime (the `walrus`
--     decoder) does NOT evaluate the policy against the replicated tuple in memory. It
--     builds a prepared statement of the form
--         select exists (select 1 from public.prices_live where ticker = <pk from the WAL>)
--     and runs it AS THE SUBSCRIBER'S ROLE, so the policy is evaluated by Postgres against
--     the live row. That is why only the KEY has to survive replication — and why DELETE is
--     the case that breaks first, since the row is gone by the time the check runs. The
--     distinction matters for the next person sizing this up: it is the identifying key
--     walrus needs, not the columns the policy happens to read. `USING (true)` below reads
--     no column at all, which is why DEFAULT is comfortably sufficient today; or
--   * a consumer that needs non-key columns out of a DELETE event — under DEFAULT a
--     DELETE payload carries the primary key and nothing else.
-- Neither exists today: the policy below is `USING (true)`, and the publisher only ever
-- upserts, so there is no DELETE path on this table at all. `FULL` costs a full old-row
-- copy in the WAL for every UPDATE, which is why it is not the default choice.
ALTER TABLE public.prices_live REPLICA IDENTITY DEFAULT;

ALTER TABLE public.prices_live ENABLE ROW LEVEL SECURITY;

-- Read: anyone may see the quotes. These are public market prices already rendered on the
-- landing page, and an authenticated visitor must not lose the feed.
--
-- This is the ONLY policy on this table, and that is the whole security model. There is
-- deliberately no INSERT, UPDATE or DELETE policy for any role — under RLS, absent policy
-- = deny — so no holder of the published anon key can write a row, and therefore no
-- forged quote can ever reach the WAL that `postgres_changes` streams from.
DROP POLICY IF EXISTS prices_live_public_read ON public.prices_live;
CREATE POLICY prices_live_public_read
  ON public.prices_live
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- Pair every GRANT SELECT with an explicit REVOKE — the convention migrations 050, 052,
-- 057 and 060 established. Migration 060 already stripped these six privileges from the
-- public roles schema-wide and via ALTER DEFAULT PRIVILEGES, so this statement should be
-- a no-op on a healthy project; it is here so that a rebuild from this repo, or a future
-- migration that re-widens the schema-level grants, cannot leave this table writable.
-- Defense in depth behind RLS, not instead of it.
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER
    ON public.prices_live
    FROM PUBLIC, anon, authenticated;

GRANT SELECT ON public.prices_live TO anon, authenticated;

-- The single writer, stated rather than inherited. `service_role` would get these
-- privileges anyway from Supabase's bootstrap default ACL on schema `public` (migration
-- 060 narrowed the defaults for `anon`/`authenticated` only), but leaving the *only*
-- writer's authority implicit in a platform ACL is exactly what 060's own comment argues
-- against. Note that `rolbypassrls` does not help here: it bypasses row-level security,
-- not table privileges, so a rebuild into a project without that default ACL would 42501
-- the edge function on every run. No DELETE — the publisher only upserts, and a feed that
-- cannot delete rows cannot be silently emptied.
GRANT SELECT, INSERT, UPDATE ON public.prices_live TO service_role;

COMMENT ON TABLE public.prices_live IS
  'Latest intraday quote per ticker, one row per symbol, written once a minute by the '
  '`prices-live` edge function under pg_cron. This is the transport for the digiquant.io '
  'live price feed: browsers subscribe to Realtime `postgres_changes` on this table '
  'rather than to the old `prices:live` broadcast channel (#1807). RLS is enabled with a '
  'read-only policy and no write policy on purpose — clients cannot write the table, so '
  'the WAL-sourced events they receive cannot be forged. service_role is the only writer.';

COMMENT ON COLUMN public.prices_live.ticker IS
  'Uppercase symbol, primary key — one row per tracked instrument, upserted in place. '
  'Matches `instruments.ticker` and `price_history.ticker` by convention, though no '
  'foreign key is declared: this is a volatile cache of the last quote, and a publisher '
  'run must not fail because a newly tracked symbol has no metadata row yet.';

COMMENT ON COLUMN public.prices_live.price IS
  'Last trade price — Finnhub /quote field `c` (current price). NOT NULL: a row with no '
  'price has nothing to publish. May legitimately be 0 for a halted or unrecognised '
  'symbol, which is why there is no positive-value CHECK; consumers gate on the value.';

COMMENT ON COLUMN public.prices_live.change IS
  'Absolute change from the prior close in quote currency — Finnhub /quote field `d`. '
  'Nullable: Finnhub omits it outside regular hours and for symbols with no prior close. '
  'Stored for completeness and for future use; the browser currently renders only '
  'change_pct.';

COMMENT ON COLUMN public.prices_live.change_pct IS
  'Percent change from the prior close in percent POINTS — Finnhub /quote field `dp`, so '
  '1.24 means +1.24%, not 0.0124. Same scale as `public_price_latest.change_pct` '
  '(migration 052) and the same convention migration 058 settled on. Nullable for the '
  'same reason as `change`.';

COMMENT ON COLUMN public.prices_live.quoted_at IS
  'When the EXCHANGE timestamped the quote — Finnhub /quote field `t`, which is unix '
  'SECONDS and must be converted (to_timestamp / epoch * 1000), not passed through as a '
  'millisecond value. This is the freshness the user cares about: it stops advancing when '
  'the market closes, and it is what a staleness check should read.';

COMMENT ON COLUMN public.prices_live.updated_at IS
  'When WE wrote the row — our clock, not the exchange''s. Advances on every publisher '
  'run even when the quote itself has not moved, so it measures pipeline liveness rather '
  'than market activity; compare against `quoted_at` to tell "the market is quiet" from '
  '"our feed is down". IMPORTANT for the publisher: the DEFAULT fires on INSERT only, so '
  'an `ON CONFLICT (ticker) DO UPDATE` must set `updated_at = now()` explicitly or every '
  'row freezes at the time of its first insert.';

-- Publish the table so Realtime emits `postgres_changes` events for it. Two things make
-- this a guarded DO block rather than a bare statement:
--   * `ALTER PUBLICATION ... ADD TABLE` raises `42710 relation is already member of
--     publication` on re-run, and this whole file must stay re-runnable.
--   * db-migrate.yml wraps the file in a single transaction, so that error would roll
--     back the table, the policy and the grants along with it — a conditional guard is
--     the only shape that survives a second application.
-- The existence and ownership checks below turn the two ways this can legitimately fail
-- into errors that name their own remedy, instead of a bare 42501 or "no such object".
-- Keep the check scoped to this publication; do NOT rebuild 062's general ownership
-- apparatus here, because unlike 062 this operation is expected to succeed.
DO $$
DECLARE
  pub_owner oid;
BEGIN
  SELECT p.pubowner INTO pub_owner
  FROM pg_catalog.pg_publication p
  WHERE p.pubname = 'supabase_realtime';

  IF pub_owner IS NULL THEN
    RAISE EXCEPTION 'migration 063: publication supabase_realtime does not exist'
      USING HINT = 'Realtime must be enabled on this project before public.prices_live '
                   'can stream postgres_changes. Enable Realtime, then re-run. Without '
                   'the publication the table is written but no browser ever sees an '
                   'update, so this raises rather than skipping.';
  END IF;

  IF NOT pg_catalog.pg_has_role(current_user, pub_owner, 'USAGE') THEN
    RAISE EXCEPTION
      'migration 063: current_user % does not own publication supabase_realtime (owner: %)',
      current_user, pub_owner::regrole
      USING ERRCODE = 'insufficient_privilege',
            HINT = 'ALTER PUBLICATION ... ADD TABLE requires ownership of the '
                   'publication. It was owned by postgres when this migration was '
                   'written (2026-08-01); if that has changed, apply as the new owner.';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_catalog.pg_publication_tables t
    WHERE t.pubname = 'supabase_realtime'
      AND t.schemaname = 'public'
      AND t.tablename = 'prices_live'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.prices_live;
  END IF;
END
$$;
