#!/usr/bin/env python3
"""Emit contract-derived artefacts from config/contract/contract.yaml.

Outputs (all under config/contract/generated/, all regenerated deterministically):

  wrangler.vars.<worker>.json  non-secret [vars] each Worker declares
  compose.env                   every compose ${NAME} the operator must supply
  env.example                  contract-derived .env.example skeleton

The checked-in root .env.example is NOT overwritten: it is hand-curated prose
carrying security guidance no generator can reproduce. check_contract.py proves
instead that every live assignment in it maps to the contract.
"""

from __future__ import annotations

import json
import pathlib
import re
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
CONTRACT = HERE / "contract.yaml"
OUTDIR = HERE / "generated"

COMPOSE_FILES = ["docker-compose.yml", "apps/digitrace-langfuse/docker-compose.local.yml"]
BANNER = "# GENERATED by config/contract/generate.py from config/contract/contract.yaml."
BANNER2 = "# Do not edit by hand; edit the contract and re-run the generator."


def strip_yaml_comments(text: str) -> str:
    out: list[str] = []
    for line in text.splitlines():
        if line.lstrip().startswith("#"):
            out.append("")
            continue
        quote = None
        buf = []
        for i, ch in enumerate(line):
            if quote:
                buf.append(ch)
                if ch == quote:
                    quote = None
            elif ch in "\"'":
                quote = ch
                buf.append(ch)
            elif ch == "#" and (i == 0 or line[i - 1] in " \t"):
                break
            else:
                buf.append(ch)
        out.append("".join(buf))
    return "\n".join(out)


def compose_forms() -> dict[str, dict]:
    """{NAME: {files, has_default, default, required}} parsed from ${...} forms."""
    found: dict[str, dict] = {}
    name_re = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
    for rel in COMPOSE_FILES:
        text = strip_yaml_comments((ROOT / rel).read_text())
        pos = 0
        while True:
            start = text.find("${", pos)
            if start < 0:
                break
            name_match = name_re.match(text, start + 2)
            if not name_match:
                pos = start + 2
                continue
            name = name_match.group(0)
            # Brace-aware: `${A:-${B:-}}` nests, so the closing brace is found by
            # counting, not by a non-greedy [^}]* that stops at the inner one.
            depth, cursor = 1, name_match.end()
            while cursor < len(text) and depth:
                if text.startswith("${", cursor):
                    depth += 1
                    cursor += 2
                elif text[cursor] == "}":
                    depth -= 1
                    cursor += 1
                else:
                    cursor += 1
            body = text[name_match.end() : cursor - 1] if depth == 0 else ""
            row = found.setdefault(name, {"files": set(), "required": False, "default": None})
            row["files"].add(rel)
            if body.startswith(":?"):
                row["required"] = True
            elif body.startswith(":-") and row["default"] is None:
                default = body[2:].strip()
                # A nested default delegates; it is not this name's own default.
                row["default"] = "" if "${" in default else default
            # Resume AT the name, not past the closing brace: a nested default
            # (`${A:-${B:-}}`) contains its own `${`, and B is a name the
            # operator may set in its own right.
            pos = name_match.end()
    return found


def main() -> int:
    contract = yaml.safe_load(CONTRACT.read_text())
    env_rows = contract["env"]
    by_name = {row["name"]: row for row in env_rows}
    forms = compose_forms()

    OUTDIR.mkdir(parents=True, exist_ok=True)

    # ---- 1. wrangler vars, one file per worker -------------------------
    workers: dict[str, dict] = {}
    for row in env_rows:
        for worker in row["sources"]["wrangler_workers"]:
            workers.setdefault(worker, {})[row["name"]] = row.get("wrangler_values", {}).get(worker)
    written = []
    for worker, variables in sorted(workers.items()):
        leaked = sorted(n for n in variables if by_name[n]["secret"])
        if leaked:
            print(f"REFUSING to emit {worker}: secret var(s) in [vars]: {leaked}")
            return 1
        payload = {"worker": worker, "source": "config/contract/contract.yaml", "vars": variables}
        path = OUTDIR / f"wrangler.vars.{worker}.json"
        path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        written.append((worker, len(variables)))

    # ---- 2. compose env ------------------------------------------------
    lines = [
        BANNER,
        BANNER2,
        "# Only names the root compose interpolates. Secrets are left empty on purpose.",
        "",
    ]
    for name in sorted(forms):
        row = by_name.get(name)
        if row is None:
            print(f"REFUSING to emit compose.env: {name} has no contract entry")
            return 1
        form = forms[name]
        flag = (
            "# REQUIRED (compose fails fast)"
            if form["required"]
            else (
                f"# default: {form['default']}" if form["default"] is not None else "# no default"
            )
        )
        lines.append(f"{name}={'' if row['secret'] else form['default'] or ''}  {flag}")
    (OUTDIR / "compose.env").write_text("\n".join(lines) + "\n", encoding="utf-8")

    # ---- 3. env.example skeleton --------------------------------------
    grouped: dict[str, list] = {}
    for row in env_rows:
        src = row["sources"]
        if src["wrangler_workers"]:
            bucket = "worker (" + ", ".join(src["wrangler_workers"]) + ")"
        elif src["compose_files"]:
            bucket = "docker compose"
        elif src["env_example_files"]:
            bucket = "local dev env.example"
        else:
            bucket = "documented only"
        grouped.setdefault(bucket, []).append(row)

    out = [
        BANNER,
        BANNER2,
        "# Contract-derived skeleton. The hand-curated root .env.example stays authoritative",
        "# for prose; check_contract.py proves every live assignment there maps here.",
        "",
    ]
    for bucket in sorted(grouped):
        out.append(f"# --- {bucket} " + "-" * max(0, 60 - len(bucket)))
        for row in sorted(grouped[bucket], key=lambda r: r["name"]):
            default = form_default(row["name"], forms)
            shown = "" if row["secret"] else (default if default is not None else "")
            out.append(f"# {row['description']}")
            out.append(f"{row['name']}={shown}")
        out.append("")
    (OUTDIR / "env.example").write_text("\n".join(out), encoding="utf-8")

    for worker, count in written:
        print(f"wrangler.vars.{worker}.json  {count} vars")
    print("compose.env", len(forms), "names")
    print("env.example", len(env_rows), "names")
    return 0


def form_default(name: str, forms: dict) -> str | None:
    row = forms.get(name)
    return None if row is None else row["default"]


if __name__ == "__main__":
    sys.exit(main())
