import { requireDigiChatAuth } from "@/lib/request-auth";
import { isEmbedChatRequest, resolveEmbedChatTenant } from "@/lib/embed-chat-tenant";
import { checkEmbedIpRateLimit } from "@/lib/embed-ip-rate-limit";
import { checkBffRateLimit } from "@/lib/bff-rate-limit";
import { fetchWithTimeout } from "@/lib/fetch-with-timeout";
import { OPENROUTER_API_BASE } from "@/lib/byok-openrouter";
import { bucketOpenRouterModels, type OpenRouterCatalogEntry } from "@/lib/openrouter-catalog";
import {
  readOpenRouterCatalogCache,
  writeOpenRouterCatalogCache,
} from "@/lib/openrouter-catalog-cache";
import { BYOK_PROVIDER_LIST, type BYOKProvider } from "@/lib/byok-providers";
import {
  bucketCatalogEntries,
  catalogEntriesFor,
  MODEL_CATALOG_FETCHED_AT,
} from "@/lib/model-catalog";

export const maxDuration = 15;

/** Reject a response body larger than this — see the design spec's Error handling
 * section on unbounded response size.
 *
 * Two checks, and only the first avoids buffering: content-length is consulted
 * before reading the body, but OpenRouter may respond chunked, in which case the
 * header is absent and the second check runs only after resp.text() has already
 * buffered everything. Acceptable here because the origin is a single fixed TLS
 * endpoint, not attacker-chosen. Note the post-buffer check counts UTF-16 code
 * units, so it admits up to 3x this many bytes: a character in U+0800–U+FFFF is
 * one UTF-16 code unit but three UTF-8 bytes. (Astral characters are the milder
 * 2x case — four bytes across two code units.) */
const MAX_RESPONSE_BYTES = 2_000_000; // 2 MB

function jsonResponse(body: unknown, status: number, extraHeaders?: Record<string, string>): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json", ...extraHeaders },
  });
}

function rateLimitResponse(message: string, retryAfterSec: number): Response {
  return jsonResponse(
    { error: "rate_limited", message },
    429,
    { "retry-after": String(retryAfterSec) },
  );
}

const UPSTREAM_UNAVAILABLE = "Model catalog is temporarily unavailable. Try again shortly.";

/** The allowlist this route is closed over. Deliberately not `isByokProvider`,
 * which coerces to a string union at the type level but would accept any string
 * typed as `BYOKProvider`; here the value comes off `URLSearchParams`, so it is
 * an untrusted `string` and needs a real membership check. */
function isByokProviderId(provider: string): provider is BYOKProvider {
  return (BYOK_PROVIDER_LIST as readonly string[]).includes(provider);
}

/**
 * GET /api/byok/models — the model catalog for the BYOK picker's tier tabs.
 *
 * Two sources, chosen per provider:
 *
 * - `openrouter` fetches OpenRouter's live `/models` listing (public; no key is
 *   needed or forwarded). Live stays live for OpenRouter because its tier
 *   buckets are derived from today's blended prices, which a vendored snapshot
 *   cannot keep up with, and because its free roster rotates.
 * - every other BYOK provider is served from the vendored models.dev catalog
 *   (`@/lib/model-catalog`, generated by `scripts/refresh_model_catalog.py`).
 *   That path performs **no fetch at all** — no URL, no timeout, no cache.
 *
 * `provider` is a closed allowlist over the five BYOK ids — 400 for anything
 * else. That is still the anti-fetch-proxy boundary: the catalog branch has no
 * upstream to be turned into a proxy, and the one branch that does fetch has its
 * endpoint hardcoded, so no attacker-chosen base URL can ever reach an outgoing
 * request from here.
 *
 * Rate-limited on BOTH the embed-IP path AND the authenticated/session path
 * (same shape as /api/byok/test) — this route needs no key at all to
 * trigger, a lower bar than /api/byok/test.
 */
export async function GET(req: Request): Promise<Response> {
  const authResult = await requireDigiChatAuth(req);
  let rateKey: string;
  if (authResult instanceof Response) {
    if (!isEmbedChatRequest(req)) return authResult;
    const embedCtx = resolveEmbedChatTenant(req);
    if (embedCtx instanceof Response) return embedCtx;
    const ipRate = checkEmbedIpRateLimit(req);
    if (!ipRate.allowed) {
      return rateLimitResponse(
        "Too many requests from this address. Try again shortly.",
        ipRate.retryAfterSec,
      );
    }
    rateKey = `byok-models:embed:${embedCtx.tenantSlug}`;
  } else {
    rateKey = `byok-models:${authResult.tenantSlug}:${authResult.ownerUserSub}`;
  }

  const rate = checkBffRateLimit(rateKey);
  if (!rate.allowed) {
    return rateLimitResponse("Too many requests. Try again shortly.", rate.retryAfterSec);
  }

  const provider = (new URL(req.url).searchParams.get("provider") || "").trim().toLowerCase();
  if (!isByokProviderId(provider)) {
    return jsonResponse(
      { error: "unsupported_provider", message: `Unknown provider: ${provider || "(none)"}.` },
      400,
    );
  }

  if (provider !== "openrouter") {
    // Vendored snapshot: synchronous, offline, and bounded by the generator's
    // own entry cap, so none of the response-size guards below apply.
    const buckets = bucketCatalogEntries(catalogEntriesFor(provider));
    return jsonResponse(
      { ok: true, ...buckets, provider, source: "catalog", fetchedAt: MODEL_CATALOG_FETCHED_AT },
      200,
    );
  }

  try {
    const cached = readOpenRouterCatalogCache();
    if (cached) {
      // No `fetchedAt` on the live path: its freshness is already bounded by the
      // cache TTL (10 min), so a catalog timestamp would be actively misleading.
      return jsonResponse({ ok: true, ...cached, provider, source: "live" }, 200);
    }

    const resp = await fetchWithTimeout(`${OPENROUTER_API_BASE}/models`, { method: "GET" });
    if (!resp.ok) {
      return jsonResponse({ error: "upstream_error", message: `OpenRouter returned HTTP ${resp.status}` }, 502);
    }
    const contentLength = Number(resp.headers.get("content-length") ?? "0");
    if (contentLength > MAX_RESPONSE_BYTES) {
      return jsonResponse({ error: "response_too_large" }, 502);
    }
    const text = await resp.text();
    if (text.length > MAX_RESPONSE_BYTES) {
      return jsonResponse({ error: "response_too_large" }, 502);
    }
    let parsed: unknown;
    try {
      parsed = JSON.parse(text);
    } catch {
      return jsonResponse({ error: "malformed_response" }, 502);
    }
    const data = (parsed as { data?: unknown }).data;
    if (!Array.isArray(data)) {
      return jsonResponse({ error: "malformed_response" }, 502);
    }
    const buckets = bucketOpenRouterModels(data as OpenRouterCatalogEntry[]);
    writeOpenRouterCatalogCache(buckets);
    return jsonResponse({ ok: true, ...buckets, provider, source: "live" }, 200);
  } catch (e) {
    console.error("[byok/models] upstream fetch failed:", e);
    return jsonResponse({ ok: false, error: "upstream_unavailable", message: UPSTREAM_UNAVAILABLE }, 502);
  }
}
