"""Unit tests for migration 063 — ``public.prices_live``, the postgres_changes feed (#1807).

Hermetic pure-SQL parse checks in the ``test_migration_060.py`` / ``test_migration_061.py``
mold: no Postgres, no network.

WHY THIS FILE REPLACED ``test_migration_062.py``
------------------------------------------------
062 tried to close the forged-broadcast hole where the hole is — RLS policies on
``realtime.messages`` — and it can never be applied. Proven read-only against the live
project on 2026-08-01: that table is owned by ``supabase_realtime_admin``, a role with ZERO
members and ZERO holders of ADMIN OPTION, so nobody reachable from here can grant it; our
connection is ``postgres`` with ``rolsuper = false`` and no membership; PostgreSQL 17.6 no
longer lets ``CREATEROLE`` imply admin over arbitrary pre-existing roles; and ``CREATE
POLICY`` requires table ownership, so it raises ``42501 must be owner of table messages``.
Only Supabase platform staff can clear that, and the dashboard SQL editor runs as the same
``postgres`` role, so it is no escape hatch either. 062 was withdrawn, its file and its test
are gone, and the number is burned. ``test_the_withdrawn_062_is_not_resurrected`` is what
notices if a revert brings it back.

WHAT THE SECURITY CONTROL ACTUALLY IS — READ BEFORE "COMPLETING" THE POLICY SET
------------------------------------------------------------------------------
The forgery hole is **abandoned, not policed**. ``prices:live`` stays an open, anon-writable
broadcast topic on this project forever: ``anon`` keeps its Supabase platform INSERT grant on
``realtime.messages`` and we cannot revoke it. It is harmless only because nothing subscribes
to it any more — an attacker's forged message lands in an empty room.

The control that replaces it is this table. RLS is enabled with exactly ONE policy
(``FOR SELECT TO anon, authenticated``) and **no write policy at all**; under RLS, absent
policy = deny. ``postgres_changes`` events are generated by Realtime from the WAL, not
accepted from clients, so an actor who cannot write the row cannot inject an event. That
makes ``test_no_policy_grants_a_write`` the security assertion of this module: it asserts an
*absence*, and an absence is precisely what a well-meaning "you forgot the INSERT policy"
patch deletes without anything else going red.

The other high-value assertion is mechanical rather than semantic:
``test_migration_is_not_self_wrapping`` runs against the RAW source, comments included,
because ``db-migrate.yml`` greps the file with ``(^|[[:space:]])begin[[:space:]]*;`` and does
not skip ``--`` lines. 063 carries a ~100-line prose header that discusses transactions, so
one unbackticked ``BEGIN;`` in that prose drops ``--single-transaction`` from the psql
invocation, splits the ledger INSERT into its own call, and lets the DDL commit with no row
in ``olympus_schema_migrations``. Nothing but this test sees that.

``pytestmark = pytest.mark.unit`` is mandatory, not decorative. The lane that collects this
directory is ``test-research-graph.yml`` (``pytest -m unit tests/dq/research/ …``); the plain
``digiquant tests`` job installs only ``digiquant[dev]``, so digigraph is absent and
``tests/dq/research/conftest.py`` ignores the whole directory there. An unmarked file is not an
error, it is silently deselected — ``pytest tests/dq/research/test_migration_061.py -m unit
--co`` reports ``23 deselected, 0 selected``, which is the state 051 and 061 are in today.
Without the marker this file would run in no lane at all.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

pytestmark = pytest.mark.unit

REPO_ROOT = Path(__file__).resolve().parents[3]
MIGRATIONS_DIR = REPO_ROOT / "digiquant" / "supabase" / "migrations"
MIGRATION_PATH = MIGRATIONS_DIR / "063_prices_live_table.sql"

TABLE = "public.prices_live"
PUBLICATION = "supabase_realtime"

# Verbatim from .github/workflows/db-migrate.yml:
#     grep -qiE '(^|[[:space:]])begin[[:space:]]*;'
# A match makes the deploy script apply the file WITHOUT --single-transaction.
SELF_WRAP_REGEX = re.compile(r"(^|[\s])begin[\s]*;", re.IGNORECASE)

# The six non-SELECT table privileges the public roles hold by Supabase platform default —
# the same list migration 060 revokes schema-wide. SELECT must never appear.
WRITE_PRIVILEGES = ("INSERT", "UPDATE", "DELETE", "TRUNCATE", "REFERENCES", "TRIGGER")

# PUBLIC is the entry that is easy to forget: naming only anon and authenticated leaves
# untouched the grant both of them inherit through PUBLIC, so the table stays writable.
REVOKED_ROLES = ("PUBLIC", "anon", "authenticated")

PUBLIC_ROLES = ("anon", "authenticated")

# The column contract three files share: this migration, the `prices-live` edge function's
# upsert, and `priceRowToLive` in the browser. postgres_changes ships the row verbatim, so a
# renamed or retyped column breaks no build — it blanks a field on digiquant.io.
EXPECTED_COLUMNS: tuple[tuple[str, str, bool], ...] = (
    ("ticker", "text", True),
    ("price", "double precision", True),
    ("change", "double precision", False),
    ("change_pct", "double precision", False),
    ("quoted_at", "timestamptz", True),
    ("updated_at", "timestamptz", True),
)

# Matches only the real statement. The DO block's RAISE HINT string also says "ALTER
# PUBLICATION ... ADD TABLE", and naming the publication and the table keeps that prose from
# satisfying the guard tests.
ADD_TABLE_REGEX = re.compile(
    rf"ALTER\s+PUBLICATION\s+{PUBLICATION}\s+ADD\s+TABLE\s+{re.escape(TABLE)}",
    re.IGNORECASE,
)


def _strip_sql_comments(sql: str) -> str:
    """Drop whole-line ``--`` comments so assertions bind to executable SQL."""
    return "\n".join(line for line in sql.splitlines() if not line.lstrip().startswith("--"))


def _policies(sql: str) -> list[dict[str, str]]:
    """Parse each ``CREATE POLICY`` statement into ``{name, table, cmd, roles, body}``.

    The ``ON <table>`` clause is part of the pattern so the phrase "CREATE POLICY" inside a
    ``RAISE ... HINT`` string cannot be mistaken for a statement. ``cmd`` is the empty string
    when the policy has no ``FOR`` clause, which in Postgres means ``FOR ALL`` — the write
    tests below treat that as the write policy it is, rather than skipping it.
    """
    out: list[dict[str, str]] = []
    for match in re.finditer(
        r"CREATE\s+POLICY\s+(?P<name>[\w\"]+)\s+ON\s+(?P<table>[\w\".]+)(?P<body>.*?);",
        sql,
        re.IGNORECASE | re.DOTALL,
    ):
        body = match.group("body")
        cmd = re.search(r"\bFOR\s+(SELECT|INSERT|UPDATE|DELETE|ALL)\b", body, re.IGNORECASE)
        roles = re.search(r"\bTO\s+([\w\s,\"]+?)(?=\bUSING\b|\bWITH\b|$)", body, re.IGNORECASE)
        out.append(
            {
                "name": match.group("name").strip('"'),
                "table": match.group("table").replace('"', "").lower(),
                "cmd": (cmd.group(1).upper() if cmd else ""),
                "roles": (roles.group(1) if roles else "").replace('"', "").lower(),
                "body": body,
                "start": str(match.start()),
            }
        )
    return out


def _role_set(clause: str) -> set[str]:
    return {role.strip().lower() for role in clause.split(",") if role.strip()}


def _grant_parts(statement: str) -> tuple[set[str], set[str]]:
    """Split one ``GRANT ... ON public.prices_live TO ...;`` into (privileges, roles)."""
    match = re.match(
        rf"GRANT\s+(?P<privs>.*?)\s+ON\s+{re.escape(TABLE)}\s+TO\s+(?P<roles>[^;]*);",
        statement.strip(),
        re.IGNORECASE | re.DOTALL,
    )
    assert match, f"unparsable GRANT: {statement}"
    privs = {priv.strip().upper() for priv in match.group("privs").split(",") if priv.strip()}
    return privs, _role_set(match.group("roles"))


@pytest.fixture(scope="module")
def raw() -> str:
    """The file exactly as ``db-migrate.yml`` greps it — comments and all."""
    assert MIGRATION_PATH.is_file(), f"migration missing: {MIGRATION_PATH}"
    return MIGRATION_PATH.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def sql(raw: str) -> str:
    """The migration with comment lines stripped, so assertions bind to executable SQL."""
    return _strip_sql_comments(raw)


@pytest.fixture(scope="module")
def columns(sql: str) -> dict[str, str]:
    """``ticker`` → ``PRIMARY KEY``: each column's constraint tail, from CREATE TABLE only.

    Scoped on purpose. The ``COMMENT ON COLUMN`` blocks further down are executable SQL and
    survive comment stripping, and the prose about ``price`` contains the literal
    ``NOT NULL`` — a whole-file grep would report the nullable columns as NOT NULL and the
    nullability half of the contract would never be checked at all.
    """
    match = re.search(
        rf"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?{re.escape(TABLE)}\s*\((?P<body>.*?)\)\s*;",
        sql,
        re.IGNORECASE | re.DOTALL,
    )
    assert match, f"no CREATE TABLE for {TABLE}"
    out: dict[str, str] = {}
    for line in match.group("body").splitlines():
        definition = line.strip().rstrip(",").strip()
        if not definition:
            continue
        name, _, rest = definition.partition(" ")
        out[name.lower()] = " ".join(rest.split())
    return out


@pytest.fixture(scope="module")
def do_block(sql: str) -> str:
    match = re.search(r"DO\s+\$\$(?P<body>.*?)\$\$\s*;", sql, re.IGNORECASE | re.DOTALL)
    assert match, "no DO $$ ... $$; block — the publication membership must be added conditionally"
    return match.group("body")


@pytest.fixture(scope="module")
def revoke(sql: str) -> re.Match[str]:
    match = re.search(rf"REVOKE\s+[^;]*?\bON\s+{re.escape(TABLE)}\b[^;]*;", sql, re.IGNORECASE)
    assert match, (
        f"no REVOKE on {TABLE} — RLS is the control, but the table privileges underneath it "
        "are the defense in depth migrations 050/052/057/060 established"
    )
    return match


@pytest.fixture(scope="module")
def grants(sql: str) -> list[re.Match[str]]:
    found = list(
        re.finditer(rf"GRANT\s+[^;]*?\bON\s+{re.escape(TABLE)}\b[^;]*;", sql, re.IGNORECASE)
    )
    assert found, f"no GRANT on {TABLE} — nothing could read or write the feed"
    return found


# ── The file itself ──────────────────────────────────────────────────────────────


def test_migration_file_exists_and_is_the_only_063() -> None:
    """A second 063_* file would apply too, and this module would not know which it audited.

    db-migrate.yml keys ``olympus_schema_migrations`` on the full filename and only emits a
    ``::warning::`` for duplicate numeric prefixes, so nothing upstream stops the split.
    """
    numbered = sorted(MIGRATIONS_DIR.glob("063_*.sql"))
    assert numbered == [MIGRATION_PATH], f"expected exactly {MIGRATION_PATH.name}, found {numbered}"


def test_the_withdrawn_062_is_not_resurrected() -> None:
    """062 cannot be applied by any role we hold; a revert that restores it wedges deploys.

    db-migrate.yml pipes every file above BASELINE_THROUGH through ``psql
    --single-transaction -v ON_ERROR_STOP=1``, so 062's ownership preflight raises, the
    transaction rolls back, and no ledger row is written — for 062 and for everything
    numbered after it in the same run.
    """
    assert not list(MIGRATIONS_DIR.glob("062_*.sql")), (
        "062 is back. It targets realtime.messages, which is owned by "
        "supabase_realtime_admin — a role with zero members that nobody can grant. Applying "
        "it raises 42501 and takes the whole migration run down with it."
    )


def test_migration_is_not_self_wrapping(raw: str) -> None:
    """Deliberately the RAW source: db-migrate.yml's grep does not skip ``--`` comments.

    The header spends ~100 lines discussing transactions and the withdrawn 062. Every
    mention of the token there is backticked so the preceding character is not whitespace;
    unbackticked, the deploy script would apply this file without --single-transaction and
    the ledger INSERT would land in a separate psql call — DDL committed, ledger silent.
    """
    hit = SELF_WRAP_REGEX.search(raw)
    assert hit is None, (
        f"a bare BEGIN; at offset {hit.start() if hit else -1} makes db-migrate.yml drop "
        "--single-transaction, so a mid-file failure cannot roll back and the migration can "
        "commit without its olympus_schema_migrations row"
    )


# ── The security control: one read policy, and no write policy at all ────────────


def test_exactly_one_policy_and_it_is_the_public_read(sql: str) -> None:
    policies = _policies(sql)
    assert len(policies) == 1, (
        f"expected exactly one policy on {TABLE}, found {[p['name'] for p in policies]} — "
        "the single read policy is the entire security model of this table"
    )
    policy = policies[0]
    assert policy["table"] == TABLE, f"policy {policy['name']} targets {policy['table']}"
    assert policy["cmd"] == "SELECT", (
        f"policy {policy['name']} is FOR {policy['cmd'] or 'ALL (no FOR clause)'}"
    )
    assert _role_set(policy["roles"]) == set(PUBLIC_ROLES), (
        f"the read policy is scoped to {policy['roles']!r}; digiquant.io subscribes with the "
        "anon key, and a signed-in visitor must not lose the feed"
    )


def test_no_policy_grants_a_write(sql: str) -> None:
    """THE fix. The absent write policy is the control, not an oversight.

    Under RLS an absent policy denies, so with no INSERT/UPDATE/DELETE/ALL policy no holder
    of the published anon key can write a row. That matters because Realtime builds
    postgres_changes payloads from the WAL rather than accepting them from clients: an actor
    who cannot write the row cannot put a forged quote on the feed at all. Adding a write
    policy for anon or authenticated here re-opens #1807 in a new place while every other
    test in this module still passes.
    """
    for policy in _policies(sql):
        command = policy["cmd"] or "ALL (no FOR clause, which Postgres reads as FOR ALL)"
        assert policy["cmd"] == "SELECT", (
            f"policy {policy['name']} is FOR {command} on {TABLE}. The absence of any write "
            "policy IS the security fix for #1807 — do not complete the policy set."
        )


def test_every_policy_is_dropped_before_it_is_created(sql: str) -> None:
    """Idempotence: db-migrate.yml re-applies a file whose ledger row is missing.

    A duplicate-policy error inside --single-transaction rolls back the table, the grants and
    the publication membership along with it.
    """
    policies = _policies(sql)
    assert policies, "no CREATE POLICY statements found"
    for policy in policies:
        drop = re.search(
            rf"DROP\s+POLICY\s+IF\s+EXISTS\s+{re.escape(policy['name'])}\b",
            sql,
            re.IGNORECASE,
        )
        assert drop is not None, f"{policy['name']} has no DROP POLICY IF EXISTS"
        assert drop.start() < int(policy["start"]), (
            f"DROP POLICY IF EXISTS {policy['name']} comes after the CREATE, so it drops the "
            "policy this run just made instead of the one a previous run left behind"
        )


def test_row_level_security_is_enabled(sql: str) -> None:
    """Without this the read policy is inert and the table's ACL is the only gate."""
    assert re.search(
        rf"ALTER\s+TABLE\s+{re.escape(TABLE)}\s+ENABLE\s+ROW\s+LEVEL\s+SECURITY\s*;",
        sql,
        re.IGNORECASE,
    ), f"{TABLE} never enables row level security"
    assert not re.search(r"DISABLE\s+ROW\s+LEVEL\s+SECURITY", sql, re.IGNORECASE), (
        "the migration disables RLS somewhere — every policy above becomes decorative"
    )


# ── Table privileges: defense in depth underneath RLS ────────────────────────────


@pytest.mark.parametrize("privilege", WRITE_PRIVILEGES)
def test_revoke_names_every_write_privilege(revoke: re.Match[str], privilege: str) -> None:
    assert re.search(rf"\b{privilege}\b", revoke.group(0), re.IGNORECASE), (
        f"{privilege} is not revoked on {TABLE}; migration 060 stripped it schema-wide, but a "
        "rebuild from this repo or a later re-widening of the schema grants would leave it"
    )


@pytest.mark.parametrize("role", REVOKED_ROLES)
def test_revoke_covers_public_and_both_client_roles(revoke: re.Match[str], role: str) -> None:
    from_clause = re.search(r"\bFROM\b(?P<roles>[^;]*)", revoke.group(0), re.IGNORECASE)
    assert from_clause, "the REVOKE has no FROM clause"
    assert re.search(rf"\b{role}\b", from_clause.group("roles"), re.IGNORECASE), (
        f"{role} is not named in the REVOKE. Naming anon and authenticated but not PUBLIC "
        "leaves the grant they both inherit through PUBLIC in place, and the table stays "
        "writable behind RLS."
    )


def test_revoke_never_strips_select(revoke: re.Match[str]) -> None:
    """A REVOKE ALL here would blank the ticker row: safeSelect turns 42501 into empty."""
    assert not re.search(r"\bSELECT\b", revoke.group(0), re.IGNORECASE)
    assert not re.search(r"REVOKE\s+ALL\b", revoke.group(0), re.IGNORECASE)


def test_revoke_precedes_the_grant(revoke: re.Match[str], grants: list[re.Match[str]]) -> None:
    """Ordering computed on executable SQL only — the header prose names GRANT first.

    A GRANT that runs before the REVOKE is undone by it, and the edge function loses the
    write it needs on the next deploy from a clean project.
    """
    first_grant = min(grant.start() for grant in grants)
    assert revoke.start() < first_grant, (
        "the GRANT runs before the REVOKE, so the REVOKE takes the granted privileges back"
    )


def test_client_roles_get_select_and_nothing_else(grants: list[re.Match[str]]) -> None:
    client_grants = [
        grant for grant in grants if _grant_parts(grant.group(0))[1] & set(PUBLIC_ROLES)
    ]
    assert len(client_grants) == 1, (
        f"expected one GRANT to the client roles, found {len(client_grants)}"
    )
    privs, roles = _grant_parts(client_grants[0].group(0))
    assert privs == {"SELECT"}, (
        f"the anon/authenticated grant carries {sorted(privs)}. Anything beyond SELECT hands "
        "the published anon key a write path that RLS would then be the only thing stopping."
    )
    assert roles == set(PUBLIC_ROLES), f"client grant targets {sorted(roles)}"


def test_service_role_is_the_only_writer(grants: list[re.Match[str]]) -> None:
    """The publisher's authority is stated, not inherited from a platform default ACL.

    ``rolbypassrls`` does not help: it bypasses row security, not table privileges, so a
    rebuild into a project without Supabase's bootstrap ACL would 42501 the edge function on
    every run.
    """
    writers = [grant for grant in grants if _grant_parts(grant.group(0))[0] & set(WRITE_PRIVILEGES)]
    assert writers, "nothing is granted write access — the prices-live function cannot upsert"
    for grant in writers:
        privs, roles = _grant_parts(grant.group(0))
        assert roles == {"service_role"}, (
            f"{sorted(privs)} granted to {sorted(roles)} on {TABLE}; service_role is the only "
            "credential that may write this table"
        )
        assert "DELETE" not in privs, (
            "the publisher only upserts; a feed that cannot delete rows cannot be emptied"
        )


# ── The postgres_changes transport ───────────────────────────────────────────────


def test_table_is_added_to_the_realtime_publication(sql: str) -> None:
    assert ADD_TABLE_REGEX.search(sql), (
        f"{TABLE} is never added to the {PUBLICATION} publication, so Realtime emits no "
        "postgres_changes events for it — rows are written and no browser ever sees one"
    )


def test_publication_add_lives_inside_the_do_block(sql: str, do_block: str) -> None:
    """A bare ALTER PUBLICATION raises 42710 on the second application.

    db-migrate.yml wraps the file in one transaction, so that error rolls back the table, the
    policy and the grants with it — the whole migration becomes un-re-runnable.
    """
    in_file = len(ADD_TABLE_REGEX.findall(sql))
    in_block = len(ADD_TABLE_REGEX.findall(do_block))
    assert in_file == in_block, (
        f"{in_file - in_block} ALTER PUBLICATION ... ADD TABLE statement(s) sit outside the "
        "guarded DO block and will raise 42710 the second time this file is applied"
    )


def test_publication_add_is_guarded_by_a_membership_check(do_block: str) -> None:
    """The guard must be the catalog lookup, not just any conditional.

    ``pg_publication_tables`` is the only check that answers "is this table already a
    member"; the block's other two IFs test the publication's existence and its ownership and
    would leave the ADD TABLE unguarded against a re-run.
    """
    add = ADD_TABLE_REGEX.search(do_block)
    assert add, "no ALTER PUBLICATION ... ADD TABLE inside the DO block"
    guard = re.search(r"IF\s+NOT\s+EXISTS\s*\(", do_block, re.IGNORECASE)
    assert guard and guard.start() < add.start(), (
        "the ALTER PUBLICATION is not wrapped in an IF NOT EXISTS ( ... ) THEN guard"
    )
    catalog = re.search(r"pg_publication_tables", do_block, re.IGNORECASE)
    assert catalog and guard.start() < catalog.start() < add.start(), (
        "the guard does not read pg_publication_tables before the ADD TABLE, so it does not "
        "actually test membership and the statement still raises 42710 on re-run"
    )


# ── The column contract ──────────────────────────────────────────────────────────


def test_create_table_is_idempotent(sql: str) -> None:
    assert re.search(
        rf"CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+{re.escape(TABLE)}\b", sql, re.IGNORECASE
    ), "CREATE TABLE without IF NOT EXISTS aborts the whole transaction on a re-run"


@pytest.mark.parametrize(("name", "sql_type", "not_null"), EXPECTED_COLUMNS)
def test_column_type_and_nullability(
    columns: dict[str, str], name: str, sql_type: str, not_null: bool
) -> None:
    """Neither half of this is caught anywhere else: there is no Deno lane and no db test.

    A wrong type surfaces as a PostgREST 22P02 in the publisher's minute-ly upsert; a wrong
    nullability surfaces the first time Finnhub omits ``d``/``dp``, which it does outside
    regular hours — a NOT NULL there would fail the whole run's upsert every evening.
    """
    assert name in columns, f"column {name} is missing from {TABLE}: have {sorted(columns)}"
    tokens = columns[name].lower().split()
    expected = sql_type.lower().split()
    assert tokens[: len(expected)] == expected, (
        f"{name} is `{columns[name]}`, expected type {sql_type}"
    )
    tail = " ".join(tokens[len(expected) :])
    if not_null:
        assert "not null" in tail or "primary key" in tail, f"{name} must be NOT NULL"
    else:
        assert "not null" not in tail, (
            f"{name} is NOT NULL, but Finnhub omits this field outside regular hours and for "
            "symbols with no prior close — the constraint would fail the entire upsert"
        )


def test_ticker_is_the_primary_key(columns: dict[str, str]) -> None:
    """The publisher upserts ON CONFLICT (ticker), and REPLICA IDENTITY DEFAULT is this key.

    Without the primary key the upsert has no conflict target and every run appends a
    duplicate row instead of updating one.
    """
    assert "primary key" in columns.get("ticker", "").lower(), (
        f"ticker is `{columns.get('ticker')}` — it must be the PRIMARY KEY"
    )
    keys = [name for name, definition in columns.items() if "primary key" in definition.lower()]
    assert keys == ["ticker"], f"expected ticker to be the only primary key, found {keys}"


def test_updated_at_defaults_to_now(columns: dict[str, str]) -> None:
    assert re.search(r"default\s+now\(\)", columns.get("updated_at", ""), re.IGNORECASE), (
        "updated_at has no DEFAULT now(); an INSERT that omits it would then violate NOT NULL"
    )


def test_no_columns_beyond_the_contract(columns: dict[str, str]) -> None:
    """The upsert enumerates these six by name and ignores anything else.

    A seventh column added here is at best never written; if it is NOT NULL without a
    default it fails every publisher run instead. Update the edge function and
    ``priceRowToLive`` in the same change, then extend EXPECTED_COLUMNS.
    """
    assert set(columns) == {name for name, _, _ in EXPECTED_COLUMNS}, (
        f"column set drifted from the contract: {sorted(columns)}"
    )
