"""Canonical DIGIQUANT_* env names with retired aliases.

Python packages stay ``digiquant.olympus.*``. Operator secrets, kill switches,
and flags use DIGIQUANT_* first. Retired OLYMPUS_* / KAIROS_* / ATLAS_* names
remain readable so live empty kill-switches stay off until rotated.

``pipeline-olympus.yml`` still exports ``OLYMPUS_ATTEMPT``; do not rename that
workflow until after the scheduled house proof. Readers accept both names.
"""

from __future__ import annotations

import os
from collections.abc import Mapping

EXECUTION_ROUTING = "DIGIQUANT_EXECUTION_ROUTING"
EXECUTION_WORKSPACE_ID = "DIGIQUANT_EXECUTION_WORKSPACE_ID"
OVERLAY_PERSIST = "DIGIQUANT_OVERLAY_PERSIST"
STAGING_USER_JWT = "DIGIQUANT_STAGING_USER_JWT"
STAGING_EMAIL = "DIGIQUANT_STAGING_EMAIL"
STAGING_PASSWORD = "DIGIQUANT_STAGING_PASSWORD"
STAGING_ANON_KEY = "DIGIQUANT_STAGING_ANON_KEY"
STAGING_FUNCTIONS_BASE = "DIGIQUANT_STAGING_FUNCTIONS_BASE"
STAGING_DIGEST_INBOX_CONFIRMED = "DIGIQUANT_STAGING_DIGEST_INBOX_CONFIRMED"
ATTEMPT = "DIGIQUANT_ATTEMPT"
BELIEFS_BACKLOG = "DIGIQUANT_BELIEFS_BACKLOG"
WEB_SEARCH = "DIGIQUANT_WEB_SEARCH"
MODEL_TIER = "DIGIQUANT_MODEL_TIER"
H6_MATERIAL_WEIGHT_PCT = "DIGIQUANT_H6_MATERIAL_WEIGHT_PCT"
H6_BOUNDARY_PRICE_DELTA = "DIGIQUANT_H6_BOUNDARY_PRICE_DELTA"
H6_SELECTION_MODE = "DIGIQUANT_H6_SELECTION_MODE"
STALE_FULL_DAYS = "DIGIQUANT_STALE_FULL_DAYS"
POSITION_RISK_FIELDS = "DIGIQUANT_POSITION_RISK_FIELDS"
PORTFOLIO_LEDGER = "DIGIQUANT_PORTFOLIO_LEDGER"
PRETRADE_RISK_MODE = "DIGIQUANT_PRETRADE_RISK_MODE"
EVIDENCE_BUNDLE_WRITER = "DIGIQUANT_EVIDENCE_BUNDLE_WRITER"
RETRIEVAL_MANIFEST_MODE = "DIGIQUANT_RETRIEVAL_MANIFEST_MODE"
CONTEXT_COMPILER_MODE = "DIGIQUANT_CONTEXT_COMPILER_MODE"
RESEARCH_POLICY_PATH = "DIGIQUANT_RESEARCH_POLICY_PATH"
SHADOW_ARTIFACT_MODE = "DIGIQUANT_SHADOW_ARTIFACT_MODE"
SHADOW_ARTIFACT_DIR = "DIGIQUANT_SHADOW_ARTIFACT_DIR"
PLANNER_MODE = "DIGIQUANT_PLANNER_MODE"
RESEARCH_ATTENTION_MODE = "DIGIQUANT_RESEARCH_ATTENTION_MODE"
RESEARCH_DATA_TOOLS = "DIGIQUANT_RESEARCH_DATA_TOOLS"
DELIBERATION_MAX_ROUNDS = "DIGIQUANT_DELIBERATION_MAX_ROUNDS"
DELIBERATION_MIN_ROUNDS = "DIGIQUANT_DELIBERATION_MIN_ROUNDS"
DEGRADED_RUN_PCT = "DIGIQUANT_DEGRADED_RUN_PCT"
REFRESH_ON_DEMAND = "DIGIQUANT_REFRESH_ON_DEMAND"
MACRO_STALE_DAYS = "DIGIQUANT_MACRO_STALE_DAYS"
MAX_ANALYSTS = "DIGIQUANT_MAX_ANALYSTS"
ONCHAIN_POSITIONING = "DIGIQUANT_ONCHAIN_POSITIONING"

# Retired names stay readable. Canonical presence (even empty) wins.
ALIASES: dict[str, tuple[str, ...]] = {
    EXECUTION_ROUTING: ("OLYMPUS_KAIROS_ROUTING",),
    EXECUTION_WORKSPACE_ID: ("OLYMPUS_KAIROS_WORKSPACE_ID",),
    OVERLAY_PERSIST: ("OLYMPUS_OVERLAY_PERSIST",),
    STAGING_USER_JWT: ("KAIROS_STAGING_USER_JWT",),
    STAGING_EMAIL: ("KAIROS_STAGING_EMAIL",),
    STAGING_PASSWORD: ("KAIROS_STAGING_PASSWORD",),
    STAGING_ANON_KEY: ("KAIROS_STAGING_ANON_KEY",),
    STAGING_FUNCTIONS_BASE: ("KAIROS_STAGING_FUNCTIONS_BASE",),
    STAGING_DIGEST_INBOX_CONFIRMED: ("KAIROS_STAGING_DIGEST_INBOX_CONFIRMED",),
    ATTEMPT: ("OLYMPUS_ATTEMPT",),
    BELIEFS_BACKLOG: ("OLYMPUS_BELIEFS_BACKLOG",),
    WEB_SEARCH: ("OLYMPUS_WEB_SEARCH",),
    MODEL_TIER: ("OLYMPUS_MODEL_TIER",),
    H6_MATERIAL_WEIGHT_PCT: ("OLYMPUS_H6_MATERIAL_WEIGHT_PCT",),
    H6_BOUNDARY_PRICE_DELTA: ("OLYMPUS_H6_BOUNDARY_PRICE_DELTA",),
    H6_SELECTION_MODE: ("OLYMPUS_H6_SELECTION_MODE",),
    STALE_FULL_DAYS: ("OLYMPUS_STALE_FULL_DAYS",),
    POSITION_RISK_FIELDS: ("OLYMPUS_POSITION_RISK_FIELDS",),
    PORTFOLIO_LEDGER: ("OLYMPUS_PORTFOLIO_LEDGER",),
    PRETRADE_RISK_MODE: ("OLYMPUS_PRETRADE_RISK_MODE",),
    EVIDENCE_BUNDLE_WRITER: ("OLYMPUS_EVIDENCE_BUNDLE_WRITER",),
    RETRIEVAL_MANIFEST_MODE: ("OLYMPUS_RETRIEVAL_MANIFEST_MODE",),
    CONTEXT_COMPILER_MODE: ("OLYMPUS_CONTEXT_COMPILER_MODE",),
    RESEARCH_POLICY_PATH: ("OLYMPUS_RESEARCH_POLICY_PATH",),
    SHADOW_ARTIFACT_MODE: ("OLYMPUS_SHADOW_ARTIFACT_MODE",),
    SHADOW_ARTIFACT_DIR: ("OLYMPUS_SHADOW_ARTIFACT_DIR",),
    PLANNER_MODE: ("OLYMPUS_PLANNER_MODE",),
    RESEARCH_ATTENTION_MODE: ("OLYMPUS_RESEARCH_ATTENTION_MODE",),
    RESEARCH_DATA_TOOLS: ("ATLAS_DATA_TOOLS",),
    DELIBERATION_MAX_ROUNDS: ("ATLAS_DELIBERATION_MAX_ROUNDS",),
    DELIBERATION_MIN_ROUNDS: ("ATLAS_DELIBERATION_MIN_ROUNDS",),
    DEGRADED_RUN_PCT: ("ATLAS_DEGRADED_RUN_PCT",),
    REFRESH_ON_DEMAND: ("ATLAS_REFRESH_ON_DEMAND",),
    MACRO_STALE_DAYS: ("ATLAS_MACRO_STALE_DAYS",),
    MAX_ANALYSTS: ("ATLAS_MAX_ANALYSTS",),
    ONCHAIN_POSITIONING: ("ATLAS_ONCHAIN_POSITIONING",),
}


def env_lookup(
    canonical: str,
    *,
    environ: Mapping[str, str] | None = None,
    default: str = "",
) -> str:
    """Read ``canonical``, else its retired aliases. Canonical presence wins."""
    env: Mapping[str, str] = os.environ if environ is None else environ
    if canonical in env:
        raw = env.get(canonical)
        return default if raw is None else str(raw)
    for alias in ALIASES.get(canonical, ()):
        if alias in env:
            raw = env.get(alias)
            return default if raw is None else str(raw)
    return default


__all__ = [
    "ALIASES",
    "ATTEMPT",
    "BELIEFS_BACKLOG",
    "CONTEXT_COMPILER_MODE",
    "DEGRADED_RUN_PCT",
    "DELIBERATION_MAX_ROUNDS",
    "DELIBERATION_MIN_ROUNDS",
    "EVIDENCE_BUNDLE_WRITER",
    "EXECUTION_ROUTING",
    "EXECUTION_WORKSPACE_ID",
    "H6_BOUNDARY_PRICE_DELTA",
    "H6_MATERIAL_WEIGHT_PCT",
    "H6_SELECTION_MODE",
    "MACRO_STALE_DAYS",
    "MAX_ANALYSTS",
    "MODEL_TIER",
    "ONCHAIN_POSITIONING",
    "OVERLAY_PERSIST",
    "PLANNER_MODE",
    "PORTFOLIO_LEDGER",
    "POSITION_RISK_FIELDS",
    "PRETRADE_RISK_MODE",
    "REFRESH_ON_DEMAND",
    "RESEARCH_ATTENTION_MODE",
    "RESEARCH_DATA_TOOLS",
    "RESEARCH_POLICY_PATH",
    "RETRIEVAL_MANIFEST_MODE",
    "SHADOW_ARTIFACT_DIR",
    "SHADOW_ARTIFACT_MODE",
    "STAGING_ANON_KEY",
    "STAGING_DIGEST_INBOX_CONFIRMED",
    "STAGING_EMAIL",
    "STAGING_FUNCTIONS_BASE",
    "STAGING_PASSWORD",
    "STAGING_USER_JWT",
    "STALE_FULL_DAYS",
    "WEB_SEARCH",
    "env_lookup",
]
