#!/usr/bin/env python3
"""Cut the org/social avatar from the canonical favicon tile.

The avatar is DERIVED, never drawn by hand. Its ink is the same `d` + block-cursor
path that ships as the favicon, read straight out of
``frontend/digithings-web/public/favicon-dg.svg`` — so the mark cannot drift from
the one on the sites. Re-run this after any change to that tile.

Why the geometry differs from the favicon rather than reusing it directly: the
favicon is drawn for a rounded-square browser tile and its ink sits off-centre,
with a half-diagonal of 48.96 in the 100-unit box. GitHub renders an avatar in a
circle in several places, and 48.96 > 50 minus a margin, so the cursor's corner
would be clipped. This scales the ink so its corners land on a 43-unit radius —
50 less a 7-unit margin for antialias spill and the ring GitHub draws — and
re-centres it to the sub-pixel.

The square is full-bleed with no baked corner radius: GitHub rounds avatars
itself, and a radius in the PNG shows as a seam inside its frame.

Usage:
    frontend/digiweb/brand/build-avatar.py          # writes avatar/*.png|svg
    frontend/digiweb/brand/build-avatar.py --check  # verify, write nothing
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

BRAND = Path(__file__).resolve().parent
REPO_ROOT = BRAND.parents[2]
SOURCE_TILE = REPO_ROOT / "frontend" / "digithings-web" / "public" / "favicon-dg.svg"
OUT_DIR = BRAND / "avatar"

# Ink bounding box of the tile, in its 100-unit viewBox: the `d` glyph spans
# x 9.8667..43.55 / y 18.4667..70.21, and the cursor rect x 50..93 / y 18.47..69.35.
INK = {"x0": 9.8667, "x1": 93.0, "y0": 18.4667, "y1": 70.21}
SAFE_RADIUS = 43.0  # 50 minus a 7-unit margin; see the module docstring.

POLARITIES = {"dark": ("#0A0E0C", "#ECEEF0"), "light": ("#FBFBF9", "#14181B")}
SIZES = (1024, 500)

TEMPLATE = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="1024" height="1024">
  <!-- GENERATED by frontend/digiweb/brand/build-avatar.py — do not hand-edit.
       Ink is the `d` + block cursor from favicon-dg.svg, scaled so its corners sit
       on a {radius}-unit radius (survives a circular crop) and centred. Square is
       full-bleed on purpose: GitHub rounds avatars itself. -->
  <rect width="100" height="100" fill="{bg}"/>
  <g fill="{ink}" transform="translate(50,50) scale({scale:.6f}) translate({dx:.4f},{dy:.4f})">
    <path d="{path}"/>
    <rect x="50.00" y="18.47" width="43.00" height="50.88"/>
  </g>
</svg>
"""


def geometry() -> tuple[float, float, float]:
    """(scale, -cx, -cy) that puts the ink centred and inside SAFE_RADIUS."""
    width = INK["x1"] - INK["x0"]
    height = INK["y1"] - INK["y0"]
    cx = (INK["x0"] + INK["x1"]) / 2
    cy = (INK["y0"] + INK["y1"]) / 2
    half_diagonal = ((width / 2) ** 2 + (height / 2) ** 2) ** 0.5
    return SAFE_RADIUS / half_diagonal, -cx, -cy


def glyph_path() -> str:
    found = re.search(r'<path d="([^"]+)"', SOURCE_TILE.read_text(encoding="utf-8"))
    if not found:
        raise SystemExit(f"no <path d=...> in {SOURCE_TILE} — has the tile changed shape?")
    return found.group(1)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()

    scale, dx, dy = geometry()
    path = glyph_path()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    svgs: dict[str, str] = {}
    for name, (bg, ink) in POLARITIES.items():
        svgs[name] = TEMPLATE.format(
            radius=int(SAFE_RADIUS), bg=bg, ink=ink, scale=scale, dx=dx, dy=dy, path=path
        )

    if args.check:
        for name, svg in svgs.items():
            target = OUT_DIR / f"digithings-avatar-{name}.svg"
            if not target.exists() or target.read_text(encoding="utf-8") != svg:
                print(f"❌  {target.name} is stale — re-run build-avatar.py", file=sys.stderr)
                return 1
        print(f"avatar: in sync with {SOURCE_TILE.name} ✅")
        return 0

    for name, svg in svgs.items():
        (OUT_DIR / f"digithings-avatar-{name}.svg").write_text(svg, encoding="utf-8")

    # Raster via sharp, already a dependency of the frontend workspace.
    script = """
const sharp = require("sharp"), fs = require("fs"), path = process.argv[1];
const sizes = %s, names = %s;
(async () => {
  for (const n of names) {
    const svg = fs.readFileSync(`${path}/digithings-avatar-${n}.svg`);
    for (const s of sizes) {
      const suffix = s === 1024 ? "" : `-${s}`;
      const f = `${path}/digithings-avatar-${n}${suffix}.png`;
      await sharp(svg, { density: 600 }).resize(s, s).png({ compressionLevel: 9 }).toFile(f);
      console.log(`  ${f.split("/").pop()}  ${s}x${s}  ${(fs.statSync(f).size / 1024).toFixed(1)}KB`);
    }
  }
})().catch((e) => { console.error(e.message); process.exit(1); });
""" % (list(SIZES), list(POLARITIES))
    subprocess.run(["node", "-e", script, str(OUT_DIR)], cwd=REPO_ROOT, check=True)
    print(f"\navatar: rebuilt from {SOURCE_TILE.relative_to(REPO_ROOT)} ✅")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
