/**
 * Baseline tape for the digiquant marketing tearsheets band.
 *
 * Symbols are the core backfill universe in
 * `digiquant/src/digiquant/data/prices/ticker_venues.py`
 * (`_NYSE_TICKERS`, `_CRYPTO_TICKERS`, `_FX_TICKERS`): ETFs (including
 * commodity and fixed-income funds), currencies, and crypto. Yahoo `=X`
 * spellings in `_FX_TICKERS` are aliases of the four FX codes already listed,
 * so the tape shows each asset once. Order matches that file.
 */
export const TAPE_SYMBOLS = [
  "SPY",
  "QQQ",
  "DIA",
  "IWB",
  "VTI",
  "MDY",
  "IJH",
  "IWM",
  "IJR",
  "XLK",
  "XLF",
  "XLE",
  "XLV",
  "XLI",
  "XLRE",
  "XLU",
  "XLY",
  "XLP",
  "XLB",
  "XLC",
  "EFA",
  "VEA",
  "VGK",
  "EWJ",
  "EWG",
  "EWU",
  "EWA",
  "EEM",
  "VWO",
  "FXI",
  "ASHR",
  "EWZ",
  "EWT",
  "EWY",
  "INDA",
  "GLD",
  "IAU",
  "SLV",
  "DBO",
  "USO",
  "BNO",
  "PDBC",
  "DJP",
  "CPER",
  "BIL",
  "SHV",
  "SHY",
  "IEF",
  "TLT",
  "AGG",
  "HYG",
  "LQD",
  "TIP",
  "EMB",
  "UUP",
  "BTC-USD",
  "ETH-USD",
  "SOL-USD",
  "XRP-USD",
  "BNB-USD",
  "TRX-USD",
  "DOGE-USD",
  "ADA-USD",
  "AVAX-USD",
  "LINK-USD",
  "DOT-USD",
  "BCH-USD",
  "LTC-USD",
  "NEAR-USD",
  "ATOM-USD",
  "XMR-USD",
  "SUI20947-USD",
  "BITO",
  "IBIT",
  "FBTC",
  "ETHA",
  "FETH",
  "GBTC",
  "EURUSD",
  "GBPUSD",
  "JPYUSD",
  "CADUSD",
] as const;
