import counts from "./module-counts.json";

/**
 * Typed read side of the per-module endpoint, MCP-tool and version facts.
 *
 * `module-counts.json` is generated by `scripts/fetch_module_counts.py` and
 * committed, the same shape as `repo-activity.json`: the site is
 * `output: "export"`, so nothing can be counted at request time.
 *
 * The two counts answer different questions and are deliberately kept apart:
 * `endpoints` is the module's public HTTP surface, counted from the committed
 * OpenAPI spec under `docs/openapi/`; `mcpTools` is how many tools it exposes
 * over MCP, counted from the decorator sites in its own server. A module can
 * have either, both, or neither.
 *
 * `versions` is the version each module declares for itself (`version` in its
 * `pyproject.toml`, or in `apps/digichat/package.json`). It is deliberately NOT
 * read from the changelog: release-please only cuts releases for digichat and
 * digiskills, so a ledger built from `releases.json` would list two modules and
 * omit the other seven.
 *
 * Null is meaningful and not zero. `digiclaw` is a CLI, `digibase` is a
 * library, and `digistore`/`digilink` are roadmap, so none of the four has a
 * spec — and printing `0 endpoints` beside them would read as "shipped and
 * exposes nothing" rather than "does not expose this at all". The same rule
 * covers `moduleVersion`: roadmap modules declare nothing, so they are null
 * rather than a made-up `0.0.0`.
 */

export type ModuleCounts = {
  endpoints: number | null;
  mcpTools: number | null;
};

const measured = counts.modules as Record<
  string,
  { endpoints?: number; mcpTools?: number } | undefined
>;

const declaredVersions = counts.versions as Record<string, string | undefined>;

export function moduleCounts(id: string): ModuleCounts {
  const facts = measured[id];
  return {
    endpoints: facts?.endpoints ?? null,
    mcpTools: facts?.mcpTools ?? null,
  };
}

/** The version the module declares for itself; null when it declares none. */
export function moduleVersion(id: string): string | null {
  return declaredVersions[id] ?? null;
}

/**
 * The counts as one line of mono micro-copy for a tile's top-right corner, e.g.
 * `22 endpoints · 127 mcp tools`. Empty string when the module has neither, so
 * the caller renders nothing rather than a stray separator.
 */
export function moduleCountLabel(id: string): string {
  const { endpoints, mcpTools } = moduleCounts(id);
  const parts: string[] = [];
  if (endpoints !== null) parts.push(`${endpoints} endpoints`);
  if (mcpTools !== null) parts.push(`${mcpTools} mcp tools`);
  return parts.join(" · ");
}
