import {
  type RepoActivitySnapshot,
  type RepoFeature,
  type RepoModuleActivity,
} from "@digithings/web";
import snapshot from "./repo-activity.json";

/**
 * Typed read side of the repository-activity snapshot.
 *
 * `repo-activity.json` is generated by `scripts/fetch_repo_activity.py` and
 * committed — the site is `output: "export"`, so there is no server at request
 * time and Cloudflare's build has no GitHub token. The shared <RepoActivity>
 * renders this object on the server, then may refresh from public GitHub after
 * hydration. A failed refresh keeps these figures. `generatedAt` is printed so
 * a stale snapshot reads as dated rather than current.
 *
 * `commits`, `pullsMerged` and `issuesClosed` cover the last `windowDays`.
 * `pullsOpen`, `issuesOpen` and `latestRelease` do NOT — they are current state.
 *
 * Deliberately absent: stars, forks, watchers.
 */

export type { RepoFeature, RepoModuleActivity, RepoActivitySnapshot };

export type RepoActivity = RepoActivitySnapshot & {
  features: RepoFeature[];
  modules: Record<string, RepoModuleActivity | undefined>;
};

export const repoActivity = snapshot as RepoActivity;

export const REPO_URL = "https://github.com/digithings-ai/digithings";
/** No trailing `.git` — git accepts either, and the shorter form fits the box. */
export const REPO_CLONE = "git clone https://github.com/digithings-ai/digithings";

/**
 * The clone command split at its last slash, so a `<wbr/>` can go between the two
 * halves: in a narrow column the command has to wrap, and its only sensible break
 * point is after the org. Derived from REPO_CLONE rather than written out again —
 * the displayed command and the copied one must not be able to drift apart.
 */
export function cloneParts(): [string, string] {
  const cut = REPO_CLONE.lastIndexOf("/") + 1;
  return [REPO_CLONE.slice(0, cut), REPO_CLONE.slice(cut)];
}
export const CONTRIBUTING_URL = `${REPO_URL}/blob/main/CONTRIBUTING.md`;

export const REPO_LIVE = {
  owner: "digithings-ai",
  repo: "digithings",
  branch: repoActivity.branch,
  windowDays: repoActivity.windowDays,
} as const;

/** `2026-08-06T12:34:56Z` -> `2026-08-06`; empty string when absent. */
export function isoDay(stamp: string | null | undefined): string {
  return stamp ? stamp.slice(0, 10) : "";
}

/** Thousands-separated, for counts that have grown past four digits. */
export function grouped(n: number): string {
  return n.toLocaleString("en-US");
}

/**
 * The activity footer appended to a module's terminal-manifest output.
 *
 * Returns null for a module with no snapshot entry — the two roadmap modules
 * (digistore, digilink) have no directory, so they have no files, no lines and no
 * last-commit date. Inventing zeroes for them would read as "shipped but empty",
 * which is the opposite of true.
 */
export function moduleActivity(id: string): string | null {
  const m = repoActivity.modules[id];
  if (!m) return null;
  const parts = [`${grouped(m.files)} files`, `${grouped(m.lines)} lines`];
  if (m.lastCommit) parts.push(`updated ${isoDay(m.lastCommit)}`);
  return parts.join("  ·  ");
}
