import { describe, expect, it } from "vitest";
import { modules } from "@digithings/web";
import { REPO_CLONE, cloneParts, isoDay, moduleActivity, repoActivity } from "./repoActivity";

/**
 * Contract tests for the committed repository-activity snapshot.
 *
 * These exist because the snapshot is generated by a Python script in a scheduled
 * workflow and consumed by TypeScript on a marketing page that promises "no
 * asterisks — every figure is countable in the repo". Nothing else sits between the
 * two: if the generator's field names drift, or a module joins the registry without
 * joining the snapshot, the page silently renders `undefined` or drops a row's
 * activity line and no build fails. The digivault registry gap was exactly that
 * failure mode — a real service missing from a count for months because nothing
 * asserted the two sources agreed.
 */
describe("repoActivity snapshot", () => {
  it("carries every velocity figure the page renders", () => {
    for (const key of [
      "commits",
      "pullsMerged",
      "issuesClosed",
      "pullsOpen",
      "issuesOpen",
    ] as const) {
      expect(typeof repoActivity[key], key).toBe("number");
      expect(repoActivity[key], key).toBeGreaterThanOrEqual(0);
    }
    expect(repoActivity.windowDays).toBe(30);
    expect(repoActivity.branch).toBe("main");
  });

  it("never carries a vanity metric", () => {
    // The generator refuses to collect these; this is the consumer-side half of
    // that rule, so adding one upstream fails here too rather than quietly
    // becoming available to render.
    const raw = repoActivity as unknown as Record<string, unknown>;
    for (const banned of ["stars", "stargazers", "forks", "watchers", "subscribers"]) {
      expect(raw[banned], banned).toBeUndefined();
    }
  });

  it("has an entry for every shipping module and none for roadmap modules", () => {
    for (const m of modules) {
      const entry = repoActivity.modules[m.id];
      if (m.tier === "roadmap") {
        expect(entry, `${m.id} is roadmap and has no directory`).toBeUndefined();
      } else {
        expect(entry, `${m.id} ships but is missing from the snapshot`).toBeDefined();
        expect(entry!.files).toBeGreaterThan(0);
        expect(entry!.lines).toBeGreaterThan(0);
      }
    }
  });

  it("renders an activity line for shipping modules only", () => {
    const shipping = modules.filter((m) => m.tier !== "roadmap");
    const roadmap = modules.filter((m) => m.tier === "roadmap");
    expect(shipping.length).toBeGreaterThan(0);
    expect(roadmap.length).toBeGreaterThan(0);

    for (const m of shipping) {
      expect(moduleActivity(m.id), m.id).toMatch(/^[\d,]+ files\s+·\s+[\d,]+ lines/);
    }
    for (const m of roadmap) {
      // null, not "0 files · 0 lines" — a zeroed line reads as shipped-but-empty.
      expect(moduleActivity(m.id), m.id).toBeNull();
    }
  });

  it("shows features as PR-linkable conventional-commit summaries", () => {
    expect(repoActivity.features.length).toBeGreaterThan(0);
    for (const f of repoActivity.features) {
      expect(Number.isInteger(f.pr) && f.pr > 0, `#${f.pr}`).toBe(true);
      expect(f.summary.length).toBeGreaterThan(0);
      // The generator strips the `feat(scope):` prefix and the trailing `(#N)`;
      // leaving either in would render the raw commit subject on the page.
      expect(f.summary).not.toMatch(/^feat[(:]/);
      expect(f.summary).not.toMatch(/\(#\d+\)$/);
    }
  });

  it("lists recent merged PRs and recently updated open issues", () => {
    expect(repoActivity.mergedPulls.length).toBeGreaterThan(0);
    expect(repoActivity.mergedPulls.length).toBeLessThanOrEqual(6);
    for (const p of repoActivity.mergedPulls) {
      expect(p.number).toBeGreaterThan(0);
      expect(p.title.length).toBeGreaterThan(0);
      expect(p.url).toContain(`/pull/${p.number}`);
    }
    expect(repoActivity.openIssues.length).toBeGreaterThan(0);
    expect(repoActivity.openIssues.length).toBeLessThanOrEqual(6);
    for (const issue of repoActivity.openIssues) {
      expect(issue.number).toBeGreaterThan(0);
      expect(issue.title.length).toBeGreaterThan(0);
      expect(issue.url).toContain(`/issues/${issue.number}`);
    }
  });

  it("shows exactly the clone command it copies", () => {
    // The <wbr/> split is presentational; rejoining the halves must give back the
    // string the copy button writes to the clipboard, or the page shows one command
    // and hands over another.
    const [head, tail] = cloneParts();
    expect(head + tail).toBe(REPO_CLONE);
    expect(head.endsWith("/")).toBe(true);
    expect(tail).not.toContain("/");
  });

  it("stamps dates the page can print without a locale", () => {
    expect(isoDay(repoActivity.generatedAt)).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    expect(isoDay(null)).toBe("");
    expect(isoDay(undefined)).toBe("");
    if (repoActivity.latestRelease) {
      expect(isoDay(repoActivity.latestRelease.publishedAt)).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(repoActivity.latestRelease.url).toContain("digithings");
    }
  });
});
