/** Pure logic behind the MCP band's demo terminal. The tool list is read from the real
 *  registry (app/_mcp-tools.json, generated by scripts/gen_mcp_manifest.py). Arguments
 *  are validated against each tool's real signature and scope; the result is a local
 *  demo, because this site has no server behind it. */

export type McpScope = "read" | "full";

export interface McpParam {
  name: string;
  type: string;
  required: boolean;
  default: unknown;
}

export interface McpTool {
  name: string;
  family: string;
  scope: McpScope;
  summary: string;
  params: McpParam[];
}

const EXAMPLES: Record<string, unknown> = {
  strategy_name: "ema_cross",
  symbols_json: '["AAPL"]',
  symbol: "AAPL",
  ticker: "AAPL",
  tickers: ["AAPL"],
  query: "momentum",
  quote_currency: "USD",
};

const baseType = (type: string) => type.replace(/\s*\|\s*None/g, "").trim();
const isNullable = (type: string) => /\|\s*None/.test(type);

/** Example arguments: every required parameter, filled with something of the right type. */
export function exampleArgs(tool: McpTool): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const p of tool.params) {
    if (!p.required) continue;
    if (p.name in EXAMPLES) {
      out[p.name] = EXAMPLES[p.name];
      continue;
    }
    switch (baseType(p.type)) {
      case "int":
        out[p.name] = 1;
        break;
      case "float":
        out[p.name] = 0;
        break;
      case "bool":
        out[p.name] = false;
        break;
      case "list[str]":
        out[p.name] = ["AAPL"];
        break;
      default:
        out[p.name] = `<${p.name}>`;
    }
  }
  return out;
}

function typeError(param: McpParam, value: unknown): string | null {
  if (value === null) return isNullable(param.type) ? null : `"${param.name}" may not be null`;
  const base = baseType(param.type);
  const ok =
    base === "str"
      ? typeof value === "string"
      : base === "int"
        ? Number.isInteger(value)
        : base === "float"
          ? typeof value === "number"
          : base === "bool"
            ? typeof value === "boolean"
            : base === "list[str]"
              ? Array.isArray(value) && value.every((v) => typeof v === "string")
              : true;
  return ok ? null : `"${param.name}" must be ${param.type}`;
}

/** Errors for a set of arguments against the tool's signature; empty when valid. */
export function validateArgs(tool: McpTool, args: Record<string, unknown>): string[] {
  const errors: string[] = [];
  const known = new Map(tool.params.map((p) => [p.name, p]));
  for (const key of Object.keys(args)) {
    if (!known.has(key)) errors.push(`unexpected argument "${key}"`);
  }
  for (const p of tool.params) {
    if (!(p.name in args)) {
      if (p.required) errors.push(`missing required argument "${p.name}"`);
      continue;
    }
    const err = typeError(p, args[p.name]);
    if (err) errors.push(err);
  }
  return errors;
}

export type DemoLine = { kind: "call" | "ok" | "err" | "out" | "mute"; text: string };

/** The transcript of one demo call. `serverScope` is the scope the demo "server" was
 *  started with: a full-scope tool is simply not registered under `read`, exactly as
 *  create_mcp_server behaves. Nothing is executed. */
export function runDemo(tool: McpTool, rawArgs: string, serverScope: McpScope): DemoLine[] {
  const lines: DemoLine[] = [{ kind: "call", text: `tools/call ${tool.name} ${rawArgs.trim() || "{}"}` }];
  if (serverScope === "read" && tool.scope === "full") {
    lines.push({ kind: "err", text: `unknown tool "${tool.name}": not registered under --scope read` });
    return lines;
  }
  let args: unknown;
  try {
    args = rawArgs.trim() ? JSON.parse(rawArgs) : {};
  } catch {
    lines.push({ kind: "err", text: "arguments are not valid JSON" });
    return lines;
  }
  if (typeof args !== "object" || args === null || Array.isArray(args)) {
    lines.push({ kind: "err", text: "arguments must be a JSON object" });
    return lines;
  }
  const errors = validateArgs(tool, args as Record<string, unknown>);
  if (errors.length > 0) {
    for (const e of errors) lines.push({ kind: "err", text: e });
    return lines;
  }
  lines.push({ kind: "ok", text: `arguments match the signature (${tool.params.filter((p) => p.required).length} required)` });
  lines.push({ kind: "ok", text: `registered under --scope ${serverScope}` });
  lines.push({
    kind: "out",
    text: JSON.stringify(
      {
        tool: tool.name,
        mode: "demo",
        executed: false,
        note: "this page has no server behind it; run the same call against your own, over stdio",
      },
      null,
      2,
    ),
  });
  return lines;
}

export function groupByFamily(tools: McpTool[]): { family: string; tools: McpTool[] }[] {
  const groups = new Map<string, McpTool[]>();
  for (const t of tools) groups.set(t.family, [...(groups.get(t.family) ?? []), t]);
  return [...groups].map(([family, list]) => ({ family, tools: list }));
}
