"""Determinism, synthetic-only and no-production guards for the local seed.

Three rules are enforced here rather than repeated in each seeder:

1. **Deterministic.** Every synthetic value derives from ``--seed`` through
   :func:`stable_uuid` or :func:`rng_for`. Nothing reads the wall clock, the
   process id or ``os.urandom`` into a seeded value.
2. **Synthetic only.** Synthetic identities use :data:`EMAIL_DOMAIN`, a
   reserved-for-testing domain. Real market data is never fetched; prices
   are generated by :func:`synthetic_ohlc`.
3. **No production writes.** :func:`require_local` refuses any endpoint
   whose host is not loopback, so a mis-set environment variable cannot
   point a seed run at a production database, R2 bucket or search index.
"""

from __future__ import annotations

import hashlib
import json
import random
import uuid
from datetime import date, timedelta
from typing import Any
from urllib.parse import urlparse

#: The seed the brief pins. Overridable per run, but this is the contract.
DEFAULT_SEED = 42

#: Namespaced so a seed id can never collide with any other uuid5 namespace
#: in the codebase (digiquant uses its own for run ids).
SEED_NS = uuid.uuid5(uuid.NAMESPACE_URL, "digithings.seed.local")

#: Reserved for testing (RFC 6761 `.invalid`/`.test` are safer but Supabase
#: auth rejects non-deliverable domains, so we use a `.local` name).
EMAIL_DOMAIN = "seed.digithings.local"

#: Hosts that are unambiguously this machine.
LOOPBACK_HOSTS = frozenset({"127.0.0.1", "localhost", "::1", "[::1]", "0.0.0.0"})


class ProductionTargetError(RuntimeError):
    """Raised when a seeder is pointed at something that is not local."""


def stable_uuid(*parts: Any) -> str:
    """Return a uuid5 derived from *parts*, stable across runs and machines."""
    return str(uuid.uuid5(SEED_NS, ":".join(str(p) for p in parts)))


def rng_for(seed: int, *parts: Any) -> random.Random:
    """Return an independent RNG stream for *parts* under *seed*.

    Per-topic streams keep one seeder's row count from shifting another
    seeder's values: adding a ticker to the market slice does not perturb
    the portfolio fixtures.
    """
    label = ":".join(str(p) for p in parts)
    return random.Random(f"{seed}:{label}")


def digest(payload: bytes | str) -> str:
    """Hex sha256 of *payload*; accepts str for convenience."""
    if isinstance(payload, str):
        payload = payload.encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def canonical_json(payload: Any) -> str:
    """Stable JSON rendering, so a digest over it is reproducible."""
    return json.dumps(payload, sort_keys=True, separators=(",", ":"))


def require_local(url: str, *, what: str) -> str:
    """Assert *url* points at this machine; return it unchanged.

    Raises :class:`ProductionTargetError` otherwise. Every seeder calls this
    before its first write, so a stray ``SUPABASE_URL`` or ``--r2-endpoint``
    pointing at production fails the run instead of writing to it.
    """
    parsed = urlparse(url if "://" in url else f"http://{url}")
    host = (parsed.hostname or "").lower()
    if host not in LOOPBACK_HOSTS:
        raise ProductionTargetError(
            f"refusing to write {what} to non-local host {host!r} ({url}); "
            "the local seed must never touch production"
        )
    return url


def demo_email(local: str) -> str:
    """A synthetic, non-deliverable demo address on the seed domain."""
    return f"{local}@{EMAIL_DOMAIN}"


def synthetic_ohlc(
    ticker: str,
    *,
    days: int,
    seed: int,
    start: date = date(2026, 1, 5),
    start_price: float = 100.0,
) -> list[dict[str, Any]]:
    """Generate *days* of synthetic daily OHLCV rows for *ticker*.

    Deliberately not real market data: a seeded geometric random walk over
    business days. The shape matches what
    :func:`scripts.backfill_market_data_r2.to_parquet_bytes` expects
    (``date`` as the sort/cast column, OHLCV numerics) so the same parquet
    encoder is used for seed and production data.
    """
    rng = rng_for(seed, "ohlc", ticker)
    price = start_price
    rows: list[dict[str, Any]] = []
    cursor = start
    while len(rows) < days:
        if cursor.weekday() < 5:  # business days only
            drift = rng.gauss(0.0004, 0.013)
            open_ = price
            close = round(max(1.0, open_ * (1.0 + drift)), 4)
            high = round(max(open_, close) * (1.0 + abs(rng.gauss(0, 0.004))), 4)
            low = round(min(open_, close) * (1.0 - abs(rng.gauss(0, 0.004))), 4)
            rows.append(
                {
                    "date": cursor,
                    "ticker": ticker,
                    "open": open_,
                    "high": high,
                    "low": low,
                    "close": close,
                    "volume": rng.randrange(1_000_000, 9_000_000),
                }
            )
            price = close
        cursor += timedelta(days=1)
    return rows
