"""Portfolio and brief fixtures (plan section 5).

The numeric series are not re-implemented here: they are generated by the
existing house seeder ``scripts/seed_digiquant_demo.py``, which already
pins ``_SEED = 42`` and upserts on natural keys. Reusing it is what makes
this leaf additive instead of a second, drifting definition of "demo NAV".

What is added here is the tenancy shape section 5 asks for: demo
workspaces plus the workspace-scoped ``documents`` rows (briefs) that
migration 105 put behind a ``(workspace_id, date, document_key)`` primary
key.
"""

from __future__ import annotations

import json
from datetime import date
from typing import Any

from scripts.seed.deterministic import DEFAULT_SEED, demo_email, rng_for, stable_uuid

DEMO_TENANT_SLUG = "seed-demo"

#: One of the 21 literals in `chk_documents_doc_type` (migration 023).
BRIEF_DOC_TYPE = "Daily Digest"

#: Demo tenants. ``system`` and ``house`` are already seeded by migration
#: 096 with their own deterministic ids, so this seed must NOT re-create
#: them; these two are additive demo tenants only.
DEMO_WORKSPACES: tuple[dict[str, Any], ...] = (
    {"slug": "seed-demo", "type": "user", "name": "Seed Demo Tenant", "plan_tier": "desk"},
    {"slug": "seed-lab", "type": "user", "name": "Seed Lab Tenant", "plan_tier": "brief"},
)

#: Demo Auth identities. Addresses are on the seed domain, never deliverable.
DEMO_USERS: tuple[dict[str, str], ...] = (
    {"local": "ada", "role": "owner"},
    {"local": "grace", "role": "member"},
)


def user_id(local: str, *, seed: int = DEFAULT_SEED) -> str:
    return stable_uuid("auth-user", seed, local)


def workspace_id(slug: str, *, seed: int = DEFAULT_SEED) -> str:
    return stable_uuid("workspace", seed, slug)


def brief_documents(
    *,
    seed: int = DEFAULT_SEED,
    workspace: str = "seed-demo",
    as_of: date = date(2026, 10, 9),
    count: int = 6,
) -> list[dict[str, Any]]:
    """Deterministic ``documents`` rows: one brief per weekday before *as_of*."""
    slug = workspace
    ws = workspace_id(slug, seed=seed)
    rows: list[dict[str, Any]] = []
    for offset in range(count):
        day = date.fromordinal(as_of.toordinal() - offset)
        rng = rng_for(seed, "brief", slug, day.isoformat())
        topic = ("rates", "equities", "credit", "commodities", "fx", "policy")[offset % 6]
        conviction = round(0.35 + rng.random() * 0.45, 2)
        rows.append(
            {
                "workspace_id": ws,
                "date": day.isoformat(),
                "document_key": f"seed/brief/{topic}/{day.isoformat()}",
                # NOT "brief": chk_documents_doc_type (migration 023) allows only
                # these 21 literals, and rejects anything else. "Daily Digest" is
                # the narrative artifact a local brief actually is.
                "doc_type": BRIEF_DOC_TYPE,
                "payload": {
                    "title": f"Seed brief — {topic} ({day.isoformat()})",
                    "summary": (
                        f"Synthetic {topic} brief for the local reference stack. "
                        "No client data, no market data, not advice."
                    ),
                    "conviction": conviction,
                    "synthetic": True,
                    "seed": seed,
                },
            }
        )
    return rows


def demo_user_rows(*, seed: int = DEFAULT_SEED) -> list[dict[str, Any]]:
    """Rows for `workspaces` + `workspace_members` (see seed.sql for the SQL form)."""
    rows: list[dict[str, Any]] = []
    for ws in DEMO_WORKSPACES:
        rows.append({"workspace_id": workspace_id(ws["slug"], seed=seed), **ws})
    for user in DEMO_USERS:
        rows.append(
            {
                "user_id": user_id(user["local"], seed=seed),
                "email": demo_email(user["local"]),
                "role": user["role"],
            }
        )
    return rows


def as_json(rows: list[dict[str, Any]]) -> str:
    """Deterministic JSON rendering, for the manifest the seed writes out."""
    return json.dumps(rows, sort_keys=True, indent=2)
