/**
 * Artifact blob storage: two backends behind one API.
 *
 * An artifact's bytes live here; its metadata lives in Postgres
 * (`src/lib/artifacts-repo.ts`). Nothing in this module reads or writes
 * metadata, and nothing here needs a database - so a blob is still servable
 * in the DB-less Cloudflare deployment, where `getDb()` returns null.
 *
 * Backend selection is explicit, never inferred from the environment:
 *
 *   - `createR2BlobStore(bucket)`   - hosted / Miniflare R2 (the Cloudflare
 *     binding shape, the same `R2Bucket` surface `market-data.ts` reads).
 *   - `createFileBlobStore(root)`   - self-host stack, one directory per
 *     artifact key.
 *
 * The digichat Cloudflare deployment is a *Container*: R2 bindings live on the
 * Worker, not inside the container, so the container path resolves to the
 * filesystem backend until an R2 binding is provisioned. Pass the bucket
 * explicitly rather than reading `env` here - that keeps this module testable
 * and keeps a credential out of reach of anything that only wanted a file.
 */
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, normalize, sep } from "node:path";

export interface ArtifactBlobStore {
  put(key: string, body: Uint8Array, contentType: string): Promise<void>;
  get(key: string): Promise<Uint8Array | null>;
  delete(key: string): Promise<void>;
}

/** Minimal structural subset of the Workers R2 binding we depend on. */
export interface R2Like {
  put(
    key: string,
    value: ArrayBuffer | Uint8Array,
    options?: { httpMetadata?: { contentType?: string } }
  ): Promise<unknown>;
  get(key: string): Promise<{ arrayBuffer(): Promise<ArrayBuffer> } | null>;
  delete(key: string): Promise<unknown>;
}

/**
 * Keys are opaque, generated by this module, and never carry a session id, a
 * ticket value or a user identifier. This is the last check before a key
 * reaches the filesystem, where `..` would be a real traversal.
 */
export function isSafeBlobKey(key: string): boolean {
  if (!key || key.length > 512) return false;
  if (key.includes("\0")) return false;
  const parts = key.split("/");
  if (parts.some((part) => part === "" || part === "." || part === "..")) return false;
  return /^[A-Za-z0-9._/-]+$/.test(key);
}

function assertSafeKey(key: string): void {
  if (!isSafeBlobKey(key)) {
    throw new Error(`unsafe artifact key`);
  }
}

export function createR2BlobStore(bucket: R2Like): ArtifactBlobStore {
  if (!bucket || typeof bucket.put !== "function" || typeof bucket.get !== "function") {
    throw new Error("artifact blob store: R2 bucket is missing required methods");
  }
  return {
    async put(key, body, contentType) {
      assertSafeKey(key);
      const copy = new Uint8Array(body);
      await bucket.put(key, copy, { httpMetadata: { contentType } });
    },
    async get(key) {
      assertSafeKey(key);
      const object = await bucket.get(key);
      if (!object) return null;
      return new Uint8Array(await object.arrayBuffer());
    },
    async delete(key) {
      assertSafeKey(key);
      await bucket.delete(key);
    },
  };
}

export function createFileBlobStore(root: string): ArtifactBlobStore {
  if (!root.trim()) {
    throw new Error("artifact blob store: filesystem root is empty");
  }
  const base = normalize(root);
  const pathFor = (key: string): string => {
    assertSafeKey(key);
    const resolved = normalize(join(base, key));
    // Belt and braces: `isSafeBlobKey` already rejects `..`, so a resolved path
    // outside the root means the check above regressed. Fail closed.
    if (resolved !== base && !resolved.startsWith(base + sep)) {
      throw new Error("unsafe artifact key");
    }
    return resolved;
  };
  return {
    async put(key, body, _contentType) {
      const target = pathFor(key);
      await mkdir(dirname(target), { recursive: true });
      await writeFile(target, body);
    },
    async get(key) {
      const target = pathFor(key);
      try {
        return new Uint8Array(await readFile(target));
      } catch (error) {
        if ((error as NodeJS.ErrnoException)?.code === "ENOENT") return null;
        throw error;
      }
    },
    async delete(key) {
      await rm(pathFor(key), { force: true });
    },
  };
}

/**
 * Self-host default. Kept out of the container's image layers so a rebuild
 * cannot silently drop artifacts, and overridable for a mounted volume.
 */
export function defaultFileBlobRoot(env: Record<string, string | undefined> = process.env): string {
  const configured = env.DIGICHAT_ARTIFACT_DIR?.trim();
  if (configured) return configured;
  return "/var/tmp/digichat-artifacts";
}
