#!/usr/bin/env python3
"""
agents_init.py — Generate platform adapter files from agents.yml.

Reads agents.yml at the repo root and writes:
  - .github/copilot-instructions.md   (GitHub Copilot workspace instructions)
  - .cursor/rules/digithings.mdc      (Cursor Agent rules, MDC format)

Run:  python3 scripts/agents_init.py
Make: make agents-init

Both output files include a "do not edit" header — regenerate with this script.
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = REPO_ROOT / "agents.yml"

GENERATED_HEADER = "<!-- Generated by scripts/agents_init.py from agents.yml — do not edit directly -->\n"


def load_config() -> dict:
    with CONFIG_PATH.open() as f:
        return yaml.safe_load(f)


def _component_table(components: list[dict]) -> str:
    rows = ["| Component | Port | Description | Agent Guide |",
            "|-----------|------|-------------|-------------|"]
    for c in components:
        port = str(c["port"]) if c["port"] else "—"
        name = c["name"]
        desc = c["description"]
        link = f"[{name}/AGENTS.md]({c['agents_doc']})"
        rows.append(f"| `{name}` | {port} | {desc} | {link} |")
    return "\n".join(rows)


def _capabilities_list(capabilities: list[dict]) -> str:
    lines = []
    for cap in capabilities:
        lines.append(f"- `make {cap['make_target']}` — {cap['description']} (`{cap['script']}`)")
    return "\n".join(lines)


def _rules_list(rules: list[str]) -> str:
    return "\n".join(f"- {r}" for r in rules)


def _scoring_section(thresholds: dict) -> str:
    lines = [
        "| Dimension | Minimum | Rubric |",
        "|-----------|---------|--------|",
    ]
    rubric_files = {
        "security": "docs/scoring/SECURITY.md",
        "quality": "docs/scoring/QUALITY.md",
        "optimization": "docs/scoring/OPTIMIZATION.md",
        "accuracy": "docs/scoring/ACCURACY.md",
    }
    for dim, score in thresholds.items():
        rubric_link = f"[{rubric_files[dim]}]({rubric_files[dim]})"
        lines.append(f"| {dim.capitalize()} | ≥{score}/10 | {rubric_link} |")
    return "\n".join(lines)


def _human_gates_list(gates: list[str]) -> str:
    return "\n".join(f"- {g}" for g in gates)


# ── Copilot instructions ───────────────────────────────────────────────────────

COPILOT_TEMPLATE = """\
{header}
# {project} — Agent Instructions

> {description}

---

## Read First (every session, in order)

1. [`AGENTS.md`](AGENTS.md) — stack-wide non-negotiable rules and autonomous development protocol
2. `{{component}}/AGENTS.md` before touching **any** component — contains pre-flight checklist, rules, test commands
3. [`docs/agents/AGENT_WORKFLOW.md`](docs/agents/AGENT_WORKFLOW.md) — end-to-end autonomous development workflow
4. [`docs/agents/COMPONENT_ROUTING.md`](docs/agents/COMPONENT_ROUTING.md) — maps file prefix → AGENTS.md + ARCHITECTURE.md + tests

---

## Non-Negotiable Rules

{rules}

---

## Components

{component_table}

---

## Scoring — Self-Score Before Opening Any PR

{scoring_table}

Full rubric criteria: [`docs/scoring/`](docs/scoring/)

---

## Agent Capabilities

{capabilities}

---

## Backlog

- [`docs/agent-backlog/INDEX.md`](docs/agent-backlog/INDEX.md) — current themes and in-progress work
- GitHub Issues labeled `agent-task` — granular tasks with acceptance criteria
- Task spec format: [`docs/agent-backlog/SPEC_TEMPLATE.md`](docs/agent-backlog/SPEC_TEMPLATE.md)

---

## Human Gate — Always Escalate For

{human_gates}

---

## Auto-Merge Eligibility

Doc-only PRs matching paths in [`docs/agent-backlog/AUTOMERGE.md`](docs/agent-backlog/AUTOMERGE.md) with label `automerge-docs` can squash-merge automatically after CI passes.
Code PRs require all score thresholds met + CI green + no human gate triggered.
"""


def generate_copilot(cfg: dict) -> str:
    return COPILOT_TEMPLATE.format(
        header=GENERATED_HEADER.strip(),
        project=cfg["project"],
        description=cfg["description"],
        rules=_rules_list(cfg["rules"]),
        component_table=_component_table(cfg["components"]),
        scoring_table=_scoring_section(cfg["scoring_thresholds"]),
        capabilities=_capabilities_list(cfg["agent_capabilities"]),
        human_gates=_human_gates_list(cfg["human_gates"]),
    )


# ── Cursor MDC rules ──────────────────────────────────────────────────────────

CURSOR_TEMPLATE = """\
---
description: {project} — project-wide agent rules. Read before making any change.
alwaysApply: true
---
{header}
# {project} — Cursor Agent Rules

> {description}

---

## Read First (every session, in order)

1. [`AGENTS.md`](AGENTS.md) — stack-wide non-negotiable rules and autonomous development protocol
2. `{{component}}/AGENTS.md` **before editing any component** — contains pre-flight checklist, rules, extension patterns
3. [`docs/agents/AGENT_WORKFLOW.md`](docs/agents/AGENT_WORKFLOW.md) — end-to-end autonomous development workflow
4. [`docs/agents/COMPONENT_ROUTING.md`](docs/agents/COMPONENT_ROUTING.md) — maps file prefix → AGENTS.md + ARCHITECTURE.md + tests

---

## Non-Negotiable Rules

{rules}

---

## Components

{component_table}

---

## Scoring — Self-Score Before Opening Any PR

{scoring_table}

Full rubric criteria: [`docs/scoring/`](docs/scoring/)

---

## Agent Capabilities (run from repo root)

{capabilities}

---

## Backlog

- [`docs/agent-backlog/INDEX.md`](docs/agent-backlog/INDEX.md) — current themes and in-progress work
- GitHub Issues labeled `agent-task` — granular tasks with acceptance criteria
- Task spec format: [`docs/agent-backlog/SPEC_TEMPLATE.md`](docs/agent-backlog/SPEC_TEMPLATE.md)

---

## Human Gate — Always Escalate For

{human_gates}
"""


def generate_cursor(cfg: dict) -> str:
    return CURSOR_TEMPLATE.format(
        header=GENERATED_HEADER.strip(),
        project=cfg["project"],
        description=cfg["description"],
        rules=_rules_list(cfg["rules"]),
        component_table=_component_table(cfg["components"]),
        scoring_table=_scoring_section(cfg["scoring_thresholds"]),
        capabilities=_capabilities_list(cfg["agent_capabilities"]),
        human_gates=_human_gates_list(cfg["human_gates"]),
    )


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> int:
    if not CONFIG_PATH.exists():
        print(f"ERROR: {CONFIG_PATH} not found", file=sys.stderr)
        return 1

    cfg = load_config()

    outputs: list[tuple[Path, str]] = [
        (REPO_ROOT / ".github" / "copilot-instructions.md", generate_copilot(cfg)),
        (REPO_ROOT / ".cursor" / "rules" / "digithings.mdc", generate_cursor(cfg)),
    ]

    for path, content in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"  wrote  {path.relative_to(REPO_ROOT)}")

    print(f"\nagents-init: OK — {len(outputs)} files generated from agents.yml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
