#!/usr/bin/env python3
"""
agents_init.py — Generate platform adapter files from agents.yml.

Reads agents.yml at the repo root and the authoritative sources under
agents/sources/, then writes:

  - .claude/agents/*.md                     (Claude Code subagents)
  - .claude/skills/<name>/SKILL.md          (Claude Code skills)
  - .claude/commands/*.md                   (Claude Code slash commands)
  - .github/copilot-instructions.md         (GitHub Copilot workspace instructions)
  - .cursor/rules/digithings.mdc            (Cursor Agent rules, MDC format)

All outputs carry a "generated — do not edit" header. Edit the sources under
agents/sources/ and agents.yml, then re-run this script.

Run:  python3 scripts/agents_init.py            # regenerate
      python3 scripts/agents_init.py --check    # CI drift guard, non-zero on drift
Make: make agents-init
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = REPO_ROOT / "agents.yml"
SOURCES_ROOT = REPO_ROOT / "agents" / "sources"

GENERATED_HEADER = "<!-- Generated by scripts/agents_init.py from agents.yml — do not edit directly. Edit the source under agents/sources/ and re-run `make agents-init`. -->\n"


def load_config() -> dict:
    with CONFIG_PATH.open() as f:
        return yaml.safe_load(f)


# ── Table / list helpers for Copilot + Cursor prose adapters ──────────────────

def _component_table(components: list[dict]) -> str:
    rows = ["| Component | Port | Description | Agent Guide |",
            "|-----------|------|-------------|-------------|"]
    for c in components:
        port = str(c["port"]) if c["port"] else "—"
        name = c["name"]
        desc = c["description"]
        link = f"[{name}/AGENTS.md]({c['agents_doc']})"
        rows.append(f"| `{name}` | {port} | {desc} | {link} |")
    return "\n".join(rows)


def _capabilities_list(capabilities: list[dict]) -> str:
    return "\n".join(
        f"- `make {cap['make_target']}` — {cap['description']} (`{cap['script']}`)"
        for cap in capabilities
    )


def _rules_list(rules: list[str]) -> str:
    return "\n".join(f"- {r}" for r in rules)


def _scoring_section(thresholds: dict) -> str:
    lines = [
        "| Dimension | Minimum | Rubric |",
        "|-----------|---------|--------|",
    ]
    rubric_files = {
        "security": "docs/scoring/SECURITY.md",
        "quality": "docs/scoring/QUALITY.md",
        "optimization": "docs/scoring/OPTIMIZATION.md",
        "accuracy": "docs/scoring/ACCURACY.md",
    }
    for dim, score in thresholds.items():
        rubric_link = f"[{rubric_files[dim]}]({rubric_files[dim]})"
        lines.append(f"| {dim.capitalize()} | ≥{score}/10 | {rubric_link} |")
    return "\n".join(lines)


def _human_gates_list(gates: list[str]) -> str:
    return "\n".join(f"- {g}" for g in gates)


def _agent_surface_prose(surface: dict) -> str:
    """Prose summary of subagents/skills/commands for Cursor + Copilot.

    Neither tool supports Claude's first-class subagents, skills, or slash commands,
    but they can still follow the same playbook if they know what each does and
    when to use it.
    """
    out = []
    subagents = surface.get("subagents") or []
    if subagents:
        out.append("**Subagents** (first-class in Claude Code; other tools should emulate the intent):\n")
        for s in subagents:
            out.append(f"- `{s['name']}` — {s['purpose']}")
        out.append("")

    skills = surface.get("skills") or []
    if skills:
        out.append("**Skills** (prompted workflows — invoke by name or when the trigger fits):\n")
        for s in skills:
            out.append(f"- `{s['name']}` — see `{s['path']}`")
        out.append("")

    commands = surface.get("commands") or []
    if commands:
        out.append("**Slash commands** (Claude Code) / prompted workflows (other tools):\n")
        for c in commands:
            out.append(f"- `{c['name']}` — see `{c['path']}`")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


# ── Copilot instructions ──────────────────────────────────────────────────────

COPILOT_TEMPLATE = """\
{header}
# {project} — Agent Instructions

> {description}

---

## Read First (every session, in order)

1. [`AGENTS.md`](AGENTS.md) — stack-wide non-negotiable rules and autonomous development protocol
2. `{{component}}/AGENTS.md` before touching **any** component — contains pre-flight checklist, rules, test commands
3. [`docs/agents/AGENT_WORKFLOW.md`](docs/agents/AGENT_WORKFLOW.md) — end-to-end autonomous development workflow
4. [`docs/agents/COMPONENT_ROUTING.md`](docs/agents/COMPONENT_ROUTING.md) — maps file prefix → AGENTS.md + ARCHITECTURE.md + tests

---

## Non-Negotiable Rules

{rules}

- **Every code change must trace to a GitHub Issue on Project #1.** Use a `task/<N>-<slug>` branch (via `make task ISSUE=N`) or include `Fixes #<N>` in the PR body. Enforced by `.github/workflows/pr-linkage.yml`.

---

## Components

{component_table}

---

## Scoring — Self-Score Before Opening Any PR

{scoring_table}

Full rubric criteria: [`docs/scoring/`](docs/scoring/)

---

## Agent Capabilities

{capabilities}

---

## Shared Agent Surface

The skills, subagents, and slash commands below are defined once under `agents/sources/` and synced to every tool via `scripts/agents_init.py`.

{agent_surface}

---

## Backlog

- Every new issue is auto-added to [Project #1](https://github.com/orgs/digithings-ai/projects/1).
- [`docs/agent-backlog/INDEX.md`](docs/agent-backlog/INDEX.md) — current themes and in-progress work
- GitHub Issues labeled `agent-task` — granular tasks with acceptance criteria
- Task spec format: [`docs/agent-backlog/SPEC_TEMPLATE.md`](docs/agent-backlog/SPEC_TEMPLATE.md)

---

## Human Gate — Always Escalate For

{human_gates}

---

## Auto-Merge Eligibility

Doc-only PRs matching paths in [`docs/agent-backlog/AUTOMERGE.md`](docs/agent-backlog/AUTOMERGE.md) with label `automerge-docs` can squash-merge automatically after CI passes.
Code PRs require all score thresholds met + CI green + no human gate triggered.
"""


def generate_copilot(cfg: dict) -> str:
    return COPILOT_TEMPLATE.format(
        header=GENERATED_HEADER.strip(),
        project=cfg["project"],
        description=cfg["description"],
        rules=_rules_list(cfg["rules"]),
        component_table=_component_table(cfg["components"]),
        scoring_table=_scoring_section(cfg["scoring_thresholds"]),
        capabilities=_capabilities_list(cfg["agent_capabilities"]),
        agent_surface=_agent_surface_prose(cfg.get("claude_code_surface", {})),
        human_gates=_human_gates_list(cfg["human_gates"]),
    )


# ── Cursor MDC rules ──────────────────────────────────────────────────────────

CURSOR_TEMPLATE = """\
---
description: {project} — project-wide agent rules. Read before making any change.
alwaysApply: true
---
{header}
# {project} — Cursor Agent Rules

> {description}

---

## Read First (every session, in order)

1. [`AGENTS.md`](AGENTS.md) — stack-wide non-negotiable rules and autonomous development protocol
2. `{{component}}/AGENTS.md` **before editing any component** — contains pre-flight checklist, rules, extension patterns
3. [`docs/agents/AGENT_WORKFLOW.md`](docs/agents/AGENT_WORKFLOW.md) — end-to-end autonomous development workflow
4. [`docs/agents/COMPONENT_ROUTING.md`](docs/agents/COMPONENT_ROUTING.md) — maps file prefix → AGENTS.md + ARCHITECTURE.md + tests

---

## Non-Negotiable Rules

{rules}

- **Every code change must trace to a GitHub Issue on Project #1.** Use a `task/<N>-<slug>` branch (via `make task ISSUE=N`) or include `Fixes #<N>` in the PR body. Enforced by `.github/workflows/pr-linkage.yml`.

---

## Components

{component_table}

---

## Scoring — Self-Score Before Opening Any PR

{scoring_table}

Full rubric criteria: [`docs/scoring/`](docs/scoring/)

---

## Agent Capabilities (run from repo root)

{capabilities}

---

## Shared Agent Surface

The skills, subagents, and slash commands below are defined once under `agents/sources/` and synced to every tool via `scripts/agents_init.py`.

{agent_surface}

---

## Backlog

- Every new issue is auto-added to [Project #1](https://github.com/orgs/digithings-ai/projects/1).
- [`docs/agent-backlog/INDEX.md`](docs/agent-backlog/INDEX.md) — current themes and in-progress work
- GitHub Issues labeled `agent-task` — granular tasks with acceptance criteria
- Task spec format: [`docs/agent-backlog/SPEC_TEMPLATE.md`](docs/agent-backlog/SPEC_TEMPLATE.md)

---

## Human Gate — Always Escalate For

{human_gates}
"""


def generate_cursor(cfg: dict) -> str:
    return CURSOR_TEMPLATE.format(
        header=GENERATED_HEADER.strip(),
        project=cfg["project"],
        description=cfg["description"],
        rules=_rules_list(cfg["rules"]),
        component_table=_component_table(cfg["components"]),
        scoring_table=_scoring_section(cfg["scoring_thresholds"]),
        capabilities=_capabilities_list(cfg["agent_capabilities"]),
        agent_surface=_agent_surface_prose(cfg.get("claude_code_surface", {})),
        human_gates=_human_gates_list(cfg["human_gates"]),
    )


# ── Claude Code artifacts (from agents/sources/) ──────────────────────────────

def _source_for_subagent(name: str) -> Path:
    return SOURCES_ROOT / "subagents" / f"{name}.md"


def _source_for_command(name: str) -> Path:
    # name is like "/spec" — strip leading slash
    bare = name.lstrip("/")
    return SOURCES_ROOT / "commands" / f"{bare}.md"


def _source_for_skill(name: str) -> Path:
    return SOURCES_ROOT / "skills" / name / "SKILL.md"


def _dest_for_subagent(name: str) -> Path:
    return REPO_ROOT / ".claude" / "agents" / f"{name}.md"


def _dest_for_command(name: str) -> Path:
    bare = name.lstrip("/")
    return REPO_ROOT / ".claude" / "commands" / f"{bare}.md"


def _dest_for_skill(name: str) -> Path:
    return REPO_ROOT / ".claude" / "skills" / name / "SKILL.md"


def _with_generated_header(source_path: Path) -> str:
    body = source_path.read_text(encoding="utf-8")
    if body.startswith("---\n"):
        # Markdown with YAML frontmatter — inject header *after* frontmatter
        # so tools that parse frontmatter don't see the HTML comment as content.
        end = body.find("\n---\n", 4)
        if end != -1:
            split = end + len("\n---\n")
            return body[:split] + GENERATED_HEADER + body[split:]
    # Plain markdown — header on top.
    return GENERATED_HEADER + body


def collect_claude_outputs(cfg: dict) -> list[tuple[Path, str]]:
    """Build the full (dest_path, content) list for the .claude/ tree.

    Validates that every declared entry has a matching source file — fails loudly
    if a declaration in agents.yml doesn't have a source under agents/sources/.
    """
    surface = cfg.get("claude_code_surface") or {}
    outputs: list[tuple[Path, str]] = []
    missing: list[str] = []

    for s in surface.get("subagents") or []:
        src = _source_for_subagent(s["name"])
        if not src.exists():
            missing.append(f"subagent '{s['name']}': expected source at {src.relative_to(REPO_ROOT)}")
            continue
        outputs.append((_dest_for_subagent(s["name"]), _with_generated_header(src)))

    for s in surface.get("skills") or []:
        src = _source_for_skill(s["name"])
        if not src.exists():
            missing.append(f"skill '{s['name']}': expected source at {src.relative_to(REPO_ROOT)}")
            continue
        outputs.append((_dest_for_skill(s["name"]), _with_generated_header(src)))

    for c in surface.get("commands") or []:
        src = _source_for_command(c["name"])
        if not src.exists():
            missing.append(f"command '{c['name']}': expected source at {src.relative_to(REPO_ROOT)}")
            continue
        outputs.append((_dest_for_command(c["name"]), _with_generated_header(src)))

    if missing:
        msg = ["ERROR: agents.yml declares entries with no source file:"]
        msg.extend(f"  - {m}" for m in missing)
        msg.append("")
        msg.append("Create the source file or remove the declaration from agents.yml.")
        raise SystemExit("\n".join(msg))

    return outputs


# ── Drift / check mode ────────────────────────────────────────────────────────

def _diff_file(path: Path, expected: str) -> list[str]:
    """Return a unified-diff list of lines if the file differs from expected; empty otherwise."""
    actual = path.read_text(encoding="utf-8") if path.exists() else ""
    if actual == expected:
        return []
    rel = path.relative_to(REPO_ROOT)
    return list(difflib.unified_diff(
        actual.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=f"{rel} (on disk)",
        tofile=f"{rel} (expected)",
        n=2,
    ))


# ── Main ──────────────────────────────────────────────────────────────────────

def _build_outputs(cfg: dict) -> list[tuple[Path, str]]:
    return [
        (REPO_ROOT / ".github" / "copilot-instructions.md", generate_copilot(cfg)),
        (REPO_ROOT / ".cursor" / "rules" / "digithings.mdc", generate_cursor(cfg)),
        *collect_claude_outputs(cfg),
    ]


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate agent-tool adapters from agents.yml.")
    ap.add_argument("--check", action="store_true",
                    help="Don't write; exit non-zero if any output would change (drift guard for CI).")
    args = ap.parse_args()

    if not CONFIG_PATH.exists():
        print(f"ERROR: {CONFIG_PATH} not found", file=sys.stderr)
        return 1

    cfg = load_config()
    outputs = _build_outputs(cfg)

    if args.check:
        drifted: list[Path] = []
        for path, content in outputs:
            diff = _diff_file(path, content)
            if diff:
                drifted.append(path)
                sys.stderr.writelines(diff)
        if drifted:
            print(
                f"\nagents-init --check: DRIFT — {len(drifted)} file(s) out of sync. Run `make agents-init`.",
                file=sys.stderr,
            )
            return 1
        print(f"agents-init --check: OK — {len(outputs)} files in sync with agents/sources/")
        return 0

    for path, content in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"  wrote  {path.relative_to(REPO_ROOT)}")

    _install_git_hooks()

    print(f"\nagents-init: OK — {len(outputs)} files generated from agents.yml + agents/sources/")
    return 0


def _install_git_hooks() -> None:
    """Copy scripts/hooks/pre-push.sh into .git/hooks/pre-push on this clone.

    Git hooks aren't tracked; this keeps every developer's clone consistent with
    the policy in scripts/hooks/. Silent if the source or .git/hooks is absent.
    """
    import shutil
    import stat

    src = REPO_ROOT / "scripts" / "hooks" / "pre-push.sh"
    dst = REPO_ROOT / ".git" / "hooks" / "pre-push"
    if not src.exists() or not dst.parent.exists():
        return
    shutil.copyfile(src, dst)
    dst.chmod(dst.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"  wrote  {dst.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    sys.exit(main())
