#!/usr/bin/env python3
"""Render the config contract (config/contract/*.yaml) into consuming artifacts.

Epic DIG-2758 S1: the contract is the source of truth; these files are not.
Every managed region is delimited by BEGIN/END config-contract markers —
never hand-edit inside them, edit the YAML and re-render:

    make config-contract        # render (writes files)
    make config-contract-check  # verify, network-free (CI; S9 consumes this)

Artifacts:
  .env.example                          identity block (both variants shown)
  apps/*/wrangler.toml [vars]           hosted identity vars (INERT keys no
                                        code reads yet: DT_VARIANT/DT_TARGET/
                                        DT_BASE_URL). Zero behavior change.
  config/generated/compose-contract.env selfhost env set for compose (S4
                                        wires it via env_file).

Only workers with contract_vars: true in services.yaml get a wrangler block.
Null contract values are never emitted (null = "unknown, do not guess").
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CONTRACT = ROOT / "config" / "contract"
GENERATED = ROOT / "config" / "generated"

BEGIN = "# BEGIN config-contract"
END = "# END config-contract"
GENERATED_BY = "generated by scripts/render_config_contract.py — do not hand-edit"

# Wrangler identity keys: hosted values only (Cloudflare is prod-only and
# these files deploy there; selfhost values must never land in [vars]).
WRANGLER_KEYS = ("DT_VARIANT", "DT_TARGET", "DT_BASE_URL")


def load_contract(root: Path = ROOT) -> dict:
    out = {}
    for name in ("variants", "services", "secrets"):
        with open(root / "config" / "contract" / f"{name}.yaml", encoding="utf-8") as fh:
            out[name] = yaml.safe_load(fh)
    return out


def identity_block(variant: dict, *, toml: bool) -> str:
    """DT_* identity lines for one variant. Raises on null (never emit nulls)."""
    lines = []
    for key in WRANGLER_KEYS:
        value = variant[key]
        if value is None:
            raise ValueError(f"contract variants.yaml: {key} is null, refusing to emit")
        lines.append(f'{key} = "{value}"' if toml else f"{key}={value}")
    return "\n".join(lines)


def replace_block(text: str, new_body: str, *, comment: str = "#") -> str:
    """Replace (or append) the marked region. Idempotent."""
    body = new_body.rstrip("\n") + "\n"
    # Markers are `# BEGIN/END config-contract` in every artifact type.
    pattern = re.compile(
        re.escape(BEGIN) + r"[^\n]*\n.*?" + re.escape(END) + r"[^\n]*",
        re.S,
    )
    replacement = f"{BEGIN} ({GENERATED_BY})\n{body}{END}"
    if pattern.search(text):
        return pattern.sub(lambda _: replacement, text, count=1)
    if not text.endswith("\n"):
        text += "\n"
    return f"{text}\n{replacement}\n"


def replace_vars_block(text: str, new_body: str) -> str:
    """Replace (or insert) the marked region INSIDE the [vars] table.

    Bare `KEY = value` lines after any other table header would belong to
    that table, so plain EOF-append is wrong when [vars] is not last.
    """
    body = new_body.rstrip("\n") + "\n"
    pattern = re.compile(
        re.escape(BEGIN) + r"[^\n]*\n.*?" + re.escape(END) + r"[^\n]*",
        re.S,
    )
    replacement = f"{BEGIN} ({GENERATED_BY})\n{body}{END}"
    # Strip any existing block first (it may sit outside [vars] from an
    # older render), then always insert fresh inside [vars].
    text = pattern.sub("", text, count=1)
    match = re.search(r"(?m)^\[vars\]\s*$", text)
    if not match:
        raise ValueError("no [vars] table found")
    nxt = re.search(r"(?m)^\[", text[match.end():])
    insert_at = match.end() + nxt.start() if nxt else len(text)
    head, tail = text[:insert_at].rstrip("\n"), text[insert_at:]
    rendered = f"{head}\n\n{replacement}\n{tail.lstrip(chr(10))}"
    rendered = re.sub(r"\n{3,}", "\n\n", rendered).rstrip("\n") + "\n"
    # Pin: the block must sit between [vars] and the next table header.
    section = re.search(r"(?ms)^\[vars\]\s*$\n(.*?)(?=^\[|\Z)", rendered)
    assert section and BEGIN in section.group(1), "contract block escaped [vars]"
    return rendered


def render_env_example(contract: dict, root: Path = ROOT) -> tuple[Path, str]:
    path = root / ".env.example"
    text = path.read_text(encoding="utf-8")
    selfhost = contract["variants"]["variants"]["selfhost"]
    hosted = contract["variants"]["variants"]["hosted"]
    body = "\n".join(
        [
            "# Variant identity — the local stack is ALWAYS selfhost (S4/S7).",
            "# Hosted (Cloudflare, prod only) shown commented for reference.",
            identity_block(selfhost, toml=False),
            f"# {identity_block(hosted, toml=False).replace(chr(10), chr(10) + '# ')}",
            "# UIs derive API/MCP URLs from DT_BASE_URL (--target selfhost|hosted).",
        ]
    )
    return path, replace_block(text, body)


def render_wrangler(contract: dict, root: Path = ROOT) -> list[tuple[Path, str]]:
    hosted = contract["variants"]["variants"]["hosted"]
    results = []
    for worker in contract["services"]["workers"]:
        if not worker.get("contract_vars"):
            continue
        path = root / worker["file"]
        text = path.read_text(encoding="utf-8")
        if "[vars]" not in text:
            raise ValueError(f"{path} has no [vars] table; fix services.yaml contract_vars")
        results.append((path, replace_vars_block(text, identity_block(hosted, toml=True))))
    return results


def render_compose_env(contract: dict, root: Path = ROOT) -> tuple[Path, str]:
    selfhost = contract["variants"]["variants"]["selfhost"]
    lines = [
        f"# {GENERATED_BY} from config/contract/.",
        "# Selfhost values. S4 wires this file into docker-compose.yml via env_file.",
        "# No secrets in this file — values render via S5 (`dt secrets render`).",
        identity_block(selfhost, toml=False),
    ]
    for entry in contract["services"]["shared_env"]:
        value = entry.get("selfhost")
        if value is None:
            continue # S2-owned or unknown locally; never emit nulls
        lines.append(f"{entry['name']}={value}")
    for key in ("api", "graph", "key", "search", "mcp", "chat"):
        url = selfhost["public_url_convention"][key]
        lines.append(f"DT_{key.upper()}_URL={url}")
    generated = root / "config" / "generated"
    generated.mkdir(parents=True, exist_ok=True)
    return generated / "compose-contract.env", "\n".join(lines) + "\n"


def collect(root: Path = ROOT) -> list[tuple[Path, str]]:
    contract = load_contract(root)
    targets: list[tuple[Path, str]] = [render_env_example(contract, root)]
    targets.extend(render_wrangler(contract, root))
    targets.append(render_compose_env(contract, root))
    return targets


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="verify artifacts match; nonzero exit on drift")
    args = parser.parse_args(argv)
    targets = collect()
    if not args.check:
        for path, content in targets:
            path.write_text(content, encoding="utf-8")
        print(f"rendered {len(targets)} artifact(s)")
        return 0
    drifted = [str(p) for p, c in targets if not p.exists() or p.read_text(encoding="utf-8") != c]
    if drifted:
        print("config-contract drift in: " + ", ".join(drifted), file=sys.stderr)
        print("run: make config-contract", file=sys.stderr)
        return 1
    print(f"config-contract clean ({len(targets)} artifact(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
