"""digithings shared platform utilities (HTTP, errors, audit redaction, metrics, optional OTel)."""

from digibase.art9 import (
    ART9_CATEGORIES,
    INGEST_PREFIXES,
    INGEST_ROUTES,
    ROUTE_KIND_INGEST,
    ROUTE_KIND_READ,
    ROUTE_UNREGISTERED,
    RouteDecision,
    ScreenResult,
    category_order,
    check_route,
    field_names,
    is_registered,
    is_under_prefix,
    iter_ingest_routes,
    no_match_reason,
    route_kind,
    screen_request,
    screen_text,
    value_patterns,
)
from digibase.cors import install_cors, resolve_cors_origins
from digibase.http import (
    current_request_id,
    install_request_id_logging,
    install_request_id_middleware,
    outbound_request_id_headers,
    outbound_service_headers,
)
from digibase.http_client import DEFAULT_TIMEOUT, async_client, sync_client
from digibase.metrics import install_metrics

__all__ = [
    "ART9_CATEGORIES",
    "DEFAULT_TIMEOUT",
    "INGEST_PREFIXES",
    "INGEST_ROUTES",
    "ROUTE_KIND_INGEST",
    "ROUTE_KIND_READ",
    "ROUTE_UNREGISTERED",
    "RouteDecision",
    "ScreenResult",
    "async_client",
    "category_order",
    "check_route",
    "current_request_id",
    "field_names",
    "install_cors",
    "install_metrics",
    "install_request_id_logging",
    "install_request_id_middleware",
    "is_registered",
    "is_under_prefix",
    "iter_ingest_routes",
    "no_match_reason",
    "outbound_request_id_headers",
    "outbound_service_headers",
    "resolve_cors_origins",
    "route_kind",
    "screen_request",
    "screen_text",
    "sync_client",
    "value_patterns",
]
