"""Canonical DIGIQUANT_* env names.

Operator secrets, kill switches, and flags use DIGIQUANT_* exclusively. The
former ``OLYMPUS_*`` / ``ATLAS_*`` / ``KAIROS_*`` read-aliases were removed once
no deployment still set them (#4295); ``ALIASES`` is retained as an empty
mapping so the module's public API and ``env_lookup`` signature stay stable.

Python packages stay ``digiquant.dashboard.*``. Workflows
(``pipeline-digiquant.yml``, ``pipeline-research-metrics.yml``,
``digiquant-pipeline.yml``) emit the canonical names.
"""

from __future__ import annotations

import os
from collections.abc import Mapping

EXECUTION_ROUTING = "DIGIQUANT_EXECUTION_ROUTING"
EXECUTION_WORKSPACE_ID = "DIGIQUANT_EXECUTION_WORKSPACE_ID"
OVERLAY_PERSIST = "DIGIQUANT_OVERLAY_PERSIST"
STAGING_USER_JWT = "DIGIQUANT_STAGING_USER_JWT"
STAGING_EMAIL = "DIGIQUANT_STAGING_EMAIL"
STAGING_PASSWORD: str = "DIGIQUANT_STAGING_PASSWORD"
STAGING_ANON_KEY = "DIGIQUANT_STAGING_ANON_KEY"
STAGING_FUNCTIONS_BASE = "DIGIQUANT_STAGING_FUNCTIONS_BASE"
STAGING_DIGEST_INBOX_CONFIRMED = "DIGIQUANT_STAGING_DIGEST_INBOX_CONFIRMED"
ATTEMPT = "DIGIQUANT_ATTEMPT"
BELIEFS_BACKLOG = "DIGIQUANT_BELIEFS_BACKLOG"
MODEL_TIER = "DIGIQUANT_MODEL_TIER"
H6_MATERIAL_WEIGHT_PCT = "DIGIQUANT_H6_MATERIAL_WEIGHT_PCT"
H6_BOUNDARY_PRICE_DELTA = "DIGIQUANT_H6_BOUNDARY_PRICE_DELTA"
H6_SELECTION_MODE = "DIGIQUANT_H6_SELECTION_MODE"
STALE_FULL_DAYS = "DIGIQUANT_STALE_FULL_DAYS"
POSITION_RISK_FIELDS = "DIGIQUANT_POSITION_RISK_FIELDS"
PORTFOLIO_LEDGER = "DIGIQUANT_PORTFOLIO_LEDGER"
PRETRADE_RISK_MODE = "DIGIQUANT_PRETRADE_RISK_MODE"
EVIDENCE_BUNDLE_WRITER = "DIGIQUANT_EVIDENCE_BUNDLE_WRITER"
RETRIEVAL_MANIFEST_MODE = "DIGIQUANT_RETRIEVAL_MANIFEST_MODE"
CONTEXT_COMPILER_MODE = "DIGIQUANT_CONTEXT_COMPILER_MODE"
RESEARCH_POLICY_PATH = "DIGIQUANT_RESEARCH_POLICY_PATH"
SHADOW_ARTIFACT_MODE = "DIGIQUANT_SHADOW_ARTIFACT_MODE"
SHADOW_ARTIFACT_DIR = "DIGIQUANT_SHADOW_ARTIFACT_DIR"
PLANNER_MODE = "DIGIQUANT_PLANNER_MODE"
RESEARCH_ATTENTION_MODE = "DIGIQUANT_RESEARCH_ATTENTION_MODE"
RESEARCH_DATA_TOOLS = "DIGIQUANT_RESEARCH_DATA_TOOLS"
DELIBERATION_MAX_ROUNDS = "DIGIQUANT_DELIBERATION_MAX_ROUNDS"
DELIBERATION_MIN_ROUNDS = "DIGIQUANT_DELIBERATION_MIN_ROUNDS"
DEGRADED_RUN_PCT = "DIGIQUANT_DEGRADED_RUN_PCT"
REFRESH_ON_DEMAND = "DIGIQUANT_REFRESH_ON_DEMAND"
MACRO_STALE_DAYS = "DIGIQUANT_MACRO_STALE_DAYS"
MAX_ANALYSTS = "DIGIQUANT_MAX_ANALYSTS"
ONCHAIN_POSITIONING = "DIGIQUANT_ONCHAIN_POSITIONING"
TOOL_ROUNDS_MAX = "DIGIQUANT_MAX_TOOL_ROUNDS"
ACCOUNTING_FINALIZER = "DIGIQUANT_ACCOUNTING_FINALIZER"
# First-party web_search tool knobs (digisearch service, #3853). Read via
# env_lookup like the DIGIQUANT_* entries; no retired aliases.
DIGISEARCH_URL = "DIGISEARCH_URL"
DIGISEARCH_WEB_SEARCH_BACKEND = "DIGISEARCH_WEB_SEARCH_BACKEND"
DIGISEARCH_SEARXNG_URL = "DIGISEARCH_SEARXNG_URL"

# No retired read-aliases remain (#4295). The mapping is retained so the public
# symbol and ``env_lookup`` fall-through behaviour stay stable; every canonical
# name is now the sole key a deployment may set.
ALIASES: dict[str, tuple[str, ...]] = {}


def env_lookup(
    canonical: str,
    *,
    environ: Mapping[str, str] | None = None,
    default: str = "",
) -> str:
    """Read ``canonical``; canonical presence (even empty) wins, else *default*."""
    env: Mapping[str, str] = os.environ if environ is None else environ
    if canonical in env:
        raw = env.get(canonical)
        return default if raw is None else str(raw)
    for alias in ALIASES.get(canonical, ()):
        if alias in env:
            raw = env.get(alias)
            return default if raw is None else str(raw)
    return default


__all__ = [
    "ACCOUNTING_FINALIZER",
    "ALIASES",
    "ATTEMPT",
    "BELIEFS_BACKLOG",
    "CONTEXT_COMPILER_MODE",
    "DEGRADED_RUN_PCT",
    "DELIBERATION_MAX_ROUNDS",
    "DELIBERATION_MIN_ROUNDS",
    "DIGISEARCH_SEARXNG_URL",
    "DIGISEARCH_URL",
    "DIGISEARCH_WEB_SEARCH_BACKEND",
    "EVIDENCE_BUNDLE_WRITER",
    "EXECUTION_ROUTING",
    "EXECUTION_WORKSPACE_ID",
    "H6_BOUNDARY_PRICE_DELTA",
    "H6_MATERIAL_WEIGHT_PCT",
    "H6_SELECTION_MODE",
    "MACRO_STALE_DAYS",
    "MAX_ANALYSTS",
    "MODEL_TIER",
    "ONCHAIN_POSITIONING",
    "OVERLAY_PERSIST",
    "PLANNER_MODE",
    "PORTFOLIO_LEDGER",
    "POSITION_RISK_FIELDS",
    "PRETRADE_RISK_MODE",
    "REFRESH_ON_DEMAND",
    "RESEARCH_ATTENTION_MODE",
    "RESEARCH_DATA_TOOLS",
    "RESEARCH_POLICY_PATH",
    "RETRIEVAL_MANIFEST_MODE",
    "SHADOW_ARTIFACT_DIR",
    "SHADOW_ARTIFACT_MODE",
    "STAGING_ANON_KEY",
    "STAGING_DIGEST_INBOX_CONFIRMED",
    "STAGING_EMAIL",
    "STAGING_FUNCTIONS_BASE",
    "STAGING_PASSWORD",
    "STAGING_USER_JWT",
    "STALE_FULL_DAYS",
    "TOOL_ROUNDS_MAX",
    "env_lookup",
]
