"""Tests for scripts/dependency_freshness.py.

Regression cover for the two parsing hazards that broke the first
implementation of the dependency freshness radar (DIG-1515):

1. `uv export` emits PEP 508 environment markers after the version on 26 of
   284 locked lines. Unsplit, `packaging.version.parse` raises and the whole
   workflow step dies before it can write any output.
2. Some PyPI release histories contain legacy non-PEP440 versions. One bad
   version must not abort the scan.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

_SPEC = importlib.util.spec_from_file_location(
    "dependency_freshness",
    Path(__file__).resolve().parents[2] / "scripts" / "dependency_freshness.py",
)
assert _SPEC and _SPEC.loader
mod = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(mod)


@pytest.fixture
def requirements(tmp_path: Path) -> Path:
    path = tmp_path / "freshness-requirements.txt"
    path.write_text(
        "# This file was autogenerated by uv\n"
        "aiohttp==3.14.3\n"
        "    # via mcp\n"
        "colorama==0.4.6 ; os_name == 'nt' or sys_platform == 'win32'\n"
        "    # via click\n"
        "pywin32==312 ; sys_platform == 'win32'\n"
        "cryptography==49.0.0\n",
        encoding="utf-8",
    )
    return path


def test_env_markers_are_stripped_from_version(requirements: Path) -> None:
    """The marker must not leak into the version we compare."""
    pinned = mod.read_pinned(requirements)
    assert pinned["colorama"] == "0.4.6"
    assert pinned["pywin32"] == "312"


def test_read_pinned_skips_comments_and_normalises(requirements: Path) -> None:
    pinned = mod.read_pinned(requirements)
    assert pinned == {
        "aiohttp": "3.14.3",
        "colorama": "0.4.6",
        "pywin32": "312",
        "cryptography": "49.0.0",
    }


def test_classify_gap_levels() -> None:
    assert mod.classify("49.0.0", "50.0.2")[0] == "major"
    assert mod.classify("2.0.51", "2.1.3")[0] == "minor"
    assert mod.classify("0.16.0", "0.16.10")[0] == "patch"
    assert mod.classify("9.1.1", "9.1.1")[0] == "current"


def test_classify_survives_unparsable_version() -> None:
    """An unparsable version is 'unknown', not an exception."""
    assert mod.classify("2004d", "2026.3.post1")[0] == "unknown"


def test_latest_stable_skips_prereleases_and_legacy() -> None:
    releases = {
        "0.3.2d": [],  # legacy, unparsable
        "1.0.0": [],
        "1.1.0rc1": [],  # pre-release
        "0.9.0": [],
    }
    assert mod.latest_stable(releases) == "1.0.0"


def test_latest_stable_returns_none_when_all_unusable() -> None:
    assert mod.latest_stable({"0.3.2d": [], "1.0.0rc1": []}) is None


def test_fetch_all_is_concurrent_not_sequential(monkeypatch: pytest.MonkeyPatch) -> None:
    """A measured run of the sequential version took 8m06s for 284 packages and
    produced 7 false `unknown` rows, because a single 10s read timeout under
    load swallowed six opentelemetry packages plus python-multipart. Unknown
    means "could not compare", so it must not be manufactured by our own
    timeout. Concurrency is the fix, and it is the only reason this test can
    distinguish the two implementations: the sleep-per-package below is what a
    sequential loop would serialise.
    """
    import time

    def slow_fetch(package: str, timeout: float = 10.0) -> str:
        time.sleep(0.2)
        return "9.9.9"

    monkeypatch.setattr(mod, "fetch_latest", slow_fetch)
    names = [f"pkg{index}" for index in range(8)]

    started = time.monotonic()
    latest = mod.fetch_all(names, workers=8)
    elapsed = time.monotonic() - started

    assert len(latest) == 8, "every package must still be compared"
    # Sequential would be >= 1.6s. Anything near it means the loop is serialised.
    assert elapsed < 1.0, f"fetch_all ran sequentially ({elapsed:.2f}s for 8 x 0.2s)"


def test_fetch_all_keeps_going_past_one_failed_package(monkeypatch: pytest.MonkeyPatch) -> None:
    """One unreadable package must not cost the other 283 their comparison."""

    def fetch(package: str, timeout: float = 10.0) -> str:
        if package == "broken":
            raise TimeoutError("read timed out")
        if package == "empty":
            return None  # release history had no usable version
        return "1.2.3"

    monkeypatch.setattr(mod, "fetch_latest", fetch)

    latest = mod.fetch_all(["broken", "empty", "fine"], workers=2)

    assert latest == {"empty": None, "fine": "1.2.3"}


def test_fetch_all_bounds_its_workers() -> None:
    """PyPI is a free public service. One unbounded thread per package is how a
    monthly radar turns into a rate-limit incident for everyone else."""
    assert 1 <= mod.DEFAULT_WORKERS <= 16


def test_a_package_with_only_prereleases_is_not_called_unknown() -> None:
    """All six opentelemetry-instrumentation packages we lock have never shipped a
    non-beta on PyPI. `unknown` means "could not compare", so calling a package
    that PyPI answered clearly about "unknown" makes the radar lie about its own
    gaps. A radar that mislabels one row drags trust down on all 284, so this
    gets its own label.
    """
    releases = {"0.64b0": [], "0.65b0": [], "0.66b1": []}
    assert mod.latest_stable(releases) is None

    # fetch_all reports "PyPI answered, no stable release" as a present None.
    report = mod.build_report(
        {"opentelemetry-instrumentation": "0.65b0"},
        {"opentelemetry-instrumentation": None},
    )

    assert "no stable release" in report["table"]
    assert "0 unknown" in report["summary"], "an all-prerelease package is not a failure"
    assert "1 no stable release" in report["summary"]


def test_unreachable_pypi_is_still_unknown() -> None:
    """The other failure mode stays honest: no answer at all is unknown."""
    report = mod.build_report({"cryptography": "49.0.0"}, {})

    assert "1 unknown" in report["summary"]
    assert "0 no stable release" in report["summary"]


def test_fetch_all_separates_no_stable_from_unreachable(monkeypatch: pytest.MonkeyPatch) -> None:
    """The three return states must survive the concurrency, or the label above
    cannot be earned: a dropped key is unreachable, a present None is no-stable."""

    def fetch(package: str, timeout: float = 10.0) -> str | None:
        if package == "unreachable":
            raise TimeoutError("read timed out")
        if package == "beta-only":
            return None
        return "1.2.3"

    monkeypatch.setattr(mod, "fetch_latest", fetch)

    latest = mod.fetch_all(["unreachable", "beta-only", "fine"], workers=2)

    assert "unreachable" not in latest, "an exception drops the key"
    assert latest["beta-only"] is None, "an all-prerelease package keeps its key"
    assert latest["fine"] == "1.2.3"


def test_fetch_all_is_empty_in_empty() -> None:
    assert mod.fetch_all([]) == {}


def test_build_report_counts_and_renders_table() -> None:
    pinned = {"cryptography": "49.0.0", "fastapi": "0.141.1"}
    latest = {"cryptography": "50.0.2", "fastapi": "0.142.2"}

    report = mod.build_report(pinned, latest)

    assert "**1 major**, 1 minor, 0 patch" in report["summary"]
    assert "| cryptography | 49.0.0 | 50.0.2 |" in report["table"]
    assert "| fastapi | 0.141.1 | 0.142.2 |" in report["table"]


def test_build_report_marks_unfetched_as_unknown() -> None:
    report = mod.build_report({"cryptography": "49.0.0"}, {})

    assert "1 unknown" in report["summary"]
    assert "| cryptography | 49.0.0 | unknown |" in report["table"]


def test_report_is_json_serialisable() -> None:
    """The workflow pipes stdout into json.load, so the shape must hold."""
    import json

    report = mod.build_report({"cryptography": "49.0.0"}, {"cryptography": "50.0.2"})
    assert set(json.loads(json.dumps(report))) == {"table", "summary"}


def test_latest_stable_skips_fully_yanked_releases() -> None:
    """A yanked release is not something `uv add` can install, so it cannot be
    "latest". Verified live against the 284-package closure: narwhals 2.27.0 has
    every file yanked, so the radar was pointing at a version uv would refuse.
    """
    releases = {
        "2.26.0": [{"filename": "narwhals-2.26.0-py3-none-any.whl", "yanked": False}],
        "2.27.0": [{"filename": "narwhals-2.27.0-py3-none-any.whl", "yanked": True}],
    }
    assert mod.latest_stable(releases) == "2.26.0"


def test_latest_stable_keeps_a_release_that_has_one_installable_file() -> None:
    """PyPI yanks per file. A release with any surviving file is still
    installable, so it must not be filtered out."""
    releases = {
        "2.26.0": [{"filename": "narwhals-2.26.0.tar.gz", "yanked": True}],
        "2.25.0": [
            {"filename": "narwhals-2.25.0.tar.gz", "yanked": True},
            {"filename": "narwhals-2.25.0-py3-none-any.whl", "yanked": False},
        ],
    }
    assert mod.latest_stable(releases) == "2.25.0"


def test_a_yanked_release_with_no_file_list_is_not_assumed_yanked() -> None:
    """Absence of evidence is not a yank. Dropping a version because PyPI
    omitted its file list would silently hide the very gap the radar reports."""
    assert mod.latest_stable({"1.0.0": []}) == "1.0.0"


def test_locked_past_the_newest_installable_is_current_not_a_negative_gap() -> None:
    """We locked a version that has since been yanked, so the newest installable
    release is behind us. A `minor`/`major` label here would say we are behind
    when we are not, and send someone to chase a downgrade."""
    assert mod.classify("2.27.0", "2.26.0") == ("current", mod.CURRENT_ICON)

    report = mod.build_report({"narwhals": "2.27.0"}, {"narwhals": "2.26.0"})
    assert "0 major" in report["summary"]
    assert "1 current" in report["summary"]
    assert "| narwhals | 2.27.0 | 2.26.0 |" in report["table"]


def test_main_writes_the_contract_the_workflow_reads(
    requirements: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The whole workflow<->script seam, and the one the rest of this file never
    touched: `main()` reads `freshness-requirements.txt` from the working
    directory and writes JSON with `table` and `summary` on stdout. Mutating
    either end (wrong filename, `print` instead of `json.dump`) left all 16
    other tests passing, so this test is the only thing standing between a
    blank table and the standing report it would overwrite.
    """
    import contextlib
    import io
    import json

    def fake_fetch_all(packages: list[str], **_: object) -> dict[str, str | None]:
        return {
            "aiohttp": "3.15.0",
            "colorama": "0.4.6",
            "pywin32": "312",
            "cryptography": "50.0.2",
        }

    monkeypatch.setattr(mod, "fetch_all", fake_fetch_all)
    monkeypatch.chdir(requirements.parent)

    stdout, stderr = io.StringIO(), io.StringIO()
    with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
        assert mod.main() == 0

    report = json.loads(stdout.getvalue())
    assert set(report) == {"table", "summary"}
    assert "| cryptography | 49.0.0 | 50.0.2 |" in report["table"]
    assert "**1 major**, 1 minor, 0 patch, 2 current" in report["summary"]
    assert "4 packages" in report["summary"]
    assert "Parsed 4 pinned packages" in stderr.getvalue()
