"""Tests for scripts/dependency_freshness.py.

Regression cover for the two parsing hazards that broke the first
implementation of the dependency freshness radar (DIG-1515):

1. `uv export` emits PEP 508 environment markers after the version on 26 of
   284 locked lines. Unsplit, `packaging.version.parse` raises and the whole
   workflow step dies before it can write any output.
2. Some PyPI release histories contain legacy non-PEP440 versions. One bad
   version must not abort the scan.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

_SPEC = importlib.util.spec_from_file_location(
    "dependency_freshness",
    Path(__file__).resolve().parents[2] / "scripts" / "dependency_freshness.py",
)
assert _SPEC and _SPEC.loader
mod = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(mod)


@pytest.fixture
def requirements(tmp_path: Path) -> Path:
    path = tmp_path / "freshness-requirements.txt"
    path.write_text(
        "# This file was autogenerated by uv\n"
        "aiohttp==3.14.3\n"
        "    # via mcp\n"
        "colorama==0.4.6 ; os_name == 'nt' or sys_platform == 'win32'\n"
        "    # via click\n"
        "pywin32==312 ; sys_platform == 'win32'\n"
        "cryptography==49.0.0\n",
        encoding="utf-8",
    )
    return path


def test_env_markers_are_stripped_from_version(requirements: Path) -> None:
    """The marker must not leak into the version we compare."""
    pinned = mod.read_pinned(requirements)
    assert pinned["colorama"] == "0.4.6"
    assert pinned["pywin32"] == "312"


def test_read_pinned_skips_comments_and_normalises(requirements: Path) -> None:
    pinned = mod.read_pinned(requirements)
    assert pinned == {
        "aiohttp": "3.14.3",
        "colorama": "0.4.6",
        "pywin32": "312",
        "cryptography": "49.0.0",
    }


def test_classify_gap_levels() -> None:
    assert mod.classify("49.0.0", "50.0.2")[0] == "major"
    assert mod.classify("2.0.51", "2.1.3")[0] == "minor"
    assert mod.classify("0.16.0", "0.16.10")[0] == "patch"
    assert mod.classify("9.1.1", "9.1.1")[0] == "current"


def test_classify_survives_unparsable_version() -> None:
    """An unparsable version is 'unknown', not an exception."""
    assert mod.classify("2004d", "2026.3.post1")[0] == "unknown"


def test_latest_stable_skips_prereleases_and_legacy() -> None:
    releases = {
        "0.3.2d": [],  # legacy, unparsable
        "1.0.0": [],
        "1.1.0rc1": [],  # pre-release
        "0.9.0": [],
    }
    assert mod.latest_stable(releases) == "1.0.0"


def test_latest_stable_returns_none_when_all_unusable() -> None:
    assert mod.latest_stable({"0.3.2d": [], "1.0.0rc1": []}) is None


def test_build_report_counts_and_renders_table() -> None:
    pinned = {"cryptography": "49.0.0", "fastapi": "0.141.1"}
    latest = {"cryptography": "50.0.2", "fastapi": "0.142.2"}

    report = mod.build_report(pinned, latest)

    assert "**1 major**, 1 minor, 0 patch" in report["summary"]
    assert "| cryptography | 49.0.0 | 50.0.2 |" in report["table"]
    assert "| fastapi | 0.141.1 | 0.142.2 |" in report["table"]


def test_build_report_marks_unfetched_as_unknown() -> None:
    report = mod.build_report({"cryptography": "49.0.0"}, {})

    assert "1 unknown" in report["summary"]
    assert "| cryptography | 49.0.0 | unknown |" in report["table"]


def test_report_is_json_serialisable() -> None:
    """The workflow pipes stdout into json.load, so the shape must hold."""
    import json

    report = mod.build_report({"cryptography": "49.0.0"}, {"cryptography": "50.0.2"})
    assert set(json.loads(json.dumps(report))) == {"table", "summary"}
